# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id$
Configuration parameters:
  url = http://en.uncyclopedia.co/wiki/Main_Page uncyclopedia
  name = uncyclopedia

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'uncyclopedia'
        self.langs = {
            'ar': u'beidipedia.wikia.com',
            'lb': u'kengencyclopedia.org',
            'is': u'is.ikkepedia.org',
            'uk': u'inciklopedia.org',
            'mo': u'uichipedia.net',
            'hy': u'angragitaran.org',
            'sl': u'butalopedija.org',
            'fo': u'fo.ikkepedia.org',
            'th': u'th.uncyclopedia.info',
            'fa': u'fa.uncyc.org',
            'zh': u'cn.uncyclopedia.wikia.com',
            'de': u'de.uncyclopedia.org',
            'no': u'ikkepedia.org',
            'ko': u'uncyclopedia.kr',
            'el': u'frikipaideia.wikia.com',
            'it': u'nonciclopedia.wikia.com',
            'zh-tw': u'uncyclopedia.tw',
            'gl': u'desgalipedia.org',
            'tlh': u'tlh.uncyc.org',
            'hr': u'hr.neciklopedija.org',
            'sr': u'sr.neciklopedija.org',
            'he': u'eincyclopedia.wikia.com',
            'bn': u'bn.uncyc.org',
            'simple': u'simple.uncyc.org',
            'sk': u'necyklopedia.wikia.com',
            'ka': u'anciklopedia.org',
            'sco': u'scotypedia.org',
            'sv': u'psyklopedin.org',
            'ja': u'ansaikuropedia.org',
            'mwl': u'cciclopedia.org',
            'lt': u'juokopedija.org',
            'zh-tw': u'uncyclopedia.hk',
            'tl': u'pekepedia.net',
            'eo': u'neciklopedio.wikia.com',
            'oc': u'oisquipedia.org',
            'ms': u'bodohpedia.org',
            'bs': u'bs.neciklopedija.org',
            'es': u'inciclopedia.wikia.com',
            'de': u'www.stupidedia.org',
            'pl': u'nonsensopedia.wikia.com',
            'ie': u'ninciclopedia.org',
            'da': u'spademanns.wikia.com',
            'ro': u'neciclopedie.org',
            'li': u'kwatsjpedia.org',
            'nn': u'ikkjepedia.org',
            'mg': u'hatsiklopedia.org',
            'la': u'uncapaedia.org',
            'id': u'tolololpedia.wikia.com',
            'lo': u'lo.uncyclopedia.info',
            'io': u'io.neciklopedio.org',
            'de': u'kamelopedia.mormo.org',
            'fy': u'unsyklopedy.org',
            'en': u'en.uncyclopedia.co',
            'tr': u'yansiklopedi.org',
            'mk': u'mk.neciklopedija.org',
            'cs': u'necyklopedie.wikia.com',
            'km': u'km.uncyclopedia.info',
            'af': u'niesiklopedia.org',
            'nl': u'oncyclopedia.net',
            'et': u'ebatsuklopeedia.org',
            'got': u'unsaiklopedia.org',
            'lv': u'lv.neciklopedija.org',
            'pt-br': u'desciclopedia.ws',
            'hu': u'unciklopedia.org',
            'fr': u'desencyclopedie.wikia.com',
            'fi': u'hiki.pedia.ws',
        }

        self.namespaces[1] = self.namespaces.get(1, {})
        self.namespaces[1][u'mg'] = [u'Discuter']
        self.namespaces[1][u'ro'] = [u'Discu\u0163ie']
        self.namespaces[1][u'zh'] = [u'\u5bf9\u8bdd', u'\u5c0d\u8a71', u'\u8ba8\u8bba', u'\u8a0e\u8ad6']
        self.namespaces[1][u'sr'] = [u'Razgovor']
        self.namespaces[1][u'mo'] = [u'Discu\u021bie', u'Discu\u0163ie']
        self.namespaces[1][u'ko'] = [u'\ud1a0']
        self.namespaces[1][u'fr'] = [u'Discuter']
        self.namespaces[1][u'km'] = [u'\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[1][u'id'] = [u'Bicara']
        self.namespaces[1][u'sk'] = [u'Koment\xe1r']
        self.namespaces[1][u'pt-br'] = [u'Discuss\xe3o']
        self.namespaces[1][u'ms'] = [u'Perbualan']
        self.namespaces[1][u'zh-tw'] = [u'\u8a0e\u8ad6', u'\u8a0e\u8ad6']
        self.namespaces[1][u'tlh'] = [u'Talk']
        self.namespaces[1][u'ja'] = [u'\u30ce\u30fc\u30c8']
        self.namespaces[1][u'mwl'] = [u'Discuss\xe3o']
        self.namespaces[2] = self.namespaces.get(2, {})
        self.namespaces[2][u'fy'] = [u'Br\xfbker']
        self.namespaces[2][u'ka'] = [u'\u10db\u10dd\u10dc\u10d0\u10ec\u10d8\u10da\u10d4']
        self.namespaces[2][u'zh'] = [u'\u7528\u6237', u'\u7528\u6236']
        self.namespaces[2][u'oc'] = [u'Utilisator']
        self.namespaces[2][u'mwl'] = [u'Usu\xe1rio', u'Utilizador', u'Utilizadora']
        self.namespaces[2][u'zh-tw'] = [u'\u7528\u6236', u'\u4f7f\u7528\u8005', u'\u7528\u6236', u'\u4f7f\u7528\u8005']
        self.namespaces[2][u'mo'] = [u'Utilizator']
        self.namespaces[2][u'de'] = [u'Benutzerin', u'Benutzerin', u'Kamel']
        self.namespaces[2][u'ko'] = [u'\uc0ac']
        self.namespaces[2][u'eo'] = [u'Vikipediisto', u'Uzulo']
        self.namespaces[2][u'got'] = [u'User']
        self.namespaces[2][u'ar'] = [u'\u0645\u0633\u062a\u062e\u062f\u0645\u0629']
        self.namespaces[2][u'pt-br'] = [u'Usu\xe1rio', u'Utilizador', u'Usu\xe1ria']
        self.namespaces[2][u'pl'] = [u'U\u017cytkownik', u'U\u017cytkowniczka']
        self.namespaces[2][u'sr'] = [u'Korisnik']
        self.namespaces[2][u'cs'] = [u'U\u017eivatelka']
        self.namespaces[2][u'lb'] = [u'Benutzer', u'Benutzerin']
        self.namespaces[2][u'mg'] = [u'Utilisateur']
        self.namespaces[2][u'gl'] = [u'Usuaria']
        self.namespaces[2][u'es'] = [u'Usuaria']
        self.namespaces[2][u'he'] = [u'\u05de\u05e9\u05ea\u05de\u05e9\u05ea']
        self.namespaces[3] = self.namespaces.get(3, {})
        self.namespaces[3][u'eo'] = [u'Vikipediista diskuto', u'Uzula diskuto', u'Uzanta diskuto']
        self.namespaces[3][u'zh'] = [u'\u7528\u6237\u5bf9\u8bdd', u'\u7528\u6236\u5c0d\u8a71', u'\u7528\u6237\u8ba8\u8bba', u'\u7528\u6236\u8a0e\u8ad6']
        self.namespaces[3][u'ko'] = [u'\uc0ac\ud1a0']
        self.namespaces[3][u'ar'] = [u'\u0646\u0642\u0627\u0634 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645\u0629']
        self.namespaces[3][u'pt-br'] = [u'Usu\xe1rio Discuss\xe3o', u'Utilizador Discuss\xe3o', u'Usu\xe1ria Discuss\xe3o']
        self.namespaces[3][u'cs'] = [u'U\u017eivatel diskuse', u'U\u017eivatelka diskuse', u'Diskuse s u\u017eivatelkou']
        self.namespaces[3][u'gl'] = [u'Conversa Usuario', u'Conversa usuaria']
        self.namespaces[3][u'id'] = [u'Bicara Pengguna']
        self.namespaces[3][u'es'] = [u'Usuario Discusi\xf3n', u'Usuaria Discusi\xf3n']
        self.namespaces[3][u'lb'] = [u'Benutzer Diskussion', u'Benutzerin Diskussion']
        self.namespaces[3][u'zh-tw'] = [u'\u7528\u6236\u8a0e\u8ad6', u'\u4f7f\u7528\u8005\u8a0e\u8ad6', u'\u7528\u6236\u8a0e\u8ad6', u'\u4f7f\u7528\u8005\u8a0e\u8ad6']
        self.namespaces[3][u'fo'] = [u'Br\xfakari kjak']
        self.namespaces[3][u'got'] = [u'User talk']
        self.namespaces[3][u'ro'] = [u'Discu\u0163ie Utilizator']
        self.namespaces[3][u'pl'] = [u'Dyskusja u\u017cytkownika', u'Dyskusja u\u017cytkowniczki']
        self.namespaces[3][u'mwl'] = [u'Usu\xe1rio Discuss\xe3o', u'Utilizador Discuss\xe3o', u'Utilizadora Discuss\xe3o']
        self.namespaces[3][u'fr'] = [u'Discussion Utilisateur']
        self.namespaces[3][u'fy'] = [u'Br\xfbker oerlis']
        self.namespaces[3][u'de'] = [u'Benutzerin Diskussion', u'Benutzerin Diskussion', u'Kamel Diskussion']
        self.namespaces[3][u'mg'] = [u'Discussion Utilisateur']
        self.namespaces[3][u'hu'] = [u'User vita']
        self.namespaces[3][u'ja'] = [u'\u5229\u7528\u8005\u2010\u4f1a\u8a71']
        self.namespaces[3][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05ea']
        self.namespaces[3][u'ka'] = [u'\u10db\u10dd\u10dc\u10d0\u10ec\u10d8\u10da\u10d8\u10e1 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0', u'\u10db\u10dd\u10db\u10ee\u10db\u10d0\u10e0\u10d4\u10d1\u10d4\u10da\u10d8 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[3][u'sr'] = [u'Razgovor sa korisnikom']
        self.namespaces[3][u'mo'] = [u'Discu\u021bie Utilizator', u'Discu\u0163ie Utilizator']
        self.namespaces[3][u'oc'] = [u'Discussion Utilisator', u'Discutida Utilisator']
        self.namespaces[3][u'km'] = [u'\u17a2\u17d2\u1793\u1780\u1794\u17d2\u179a\u17be\u1794\u17d2\u179a\u17b6\u179f\u17cb-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[3][u'sk'] = [u'Koment\xe1r k redaktorovi']
        self.namespaces[3][u'ms'] = [u'Perbualan Pengguna']
        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4][u'el'] = [u'\u03a6\u03c1\u03b9\u03ba\u03b7\u03c0\u03b1\u03af\u03b4\u03b5\u03b9\u03b1']
        self.namespaces[4][u'sco'] = [u'Scotypedia']
        self.namespaces[4][u'en'] = [u'Uncyclopedia']
        self.namespaces[4][u'zh'] = [u'\u4f2a\u57fa\u767e\u79d1']
        self.namespaces[4][u'io'] = [u'Neciklopedio']
        self.namespaces[4][u'af'] = [u'Niesiklopedia']
        self.namespaces[4][u'simple'] = [u'Uncyclopedia']
        self.namespaces[4][u'oc'] = [u'Oisquipedia']
        self.namespaces[4][u'is'] = [u'Ekkipedia']
        self.namespaces[4][u'it'] = [u'Nonciclopedia']
        self.namespaces[4][u'ar'] = [u'\u0628\u064a\u0636\u064a\u067e\u064a\u062f\u064a\u0627']
        self.namespaces[4][u'pt-br'] = [u'Desciclop\xe9dia', u'DP']
        self.namespaces[4][u'km'] = [u'Uncyclopedia']
        self.namespaces[4][u'eo'] = [u'Neciklopedio']
        self.namespaces[4][u'fi'] = [u'Hikipedia']
        self.namespaces[4][u'cs'] = [u'Necyklopedie']
        self.namespaces[4][u'et'] = [u'Ebats\xfcklopeedia']
        self.namespaces[4][u'gl'] = [u'Desgalipedia']
        self.namespaces[4][u'ie'] = [u'Ninciclopedia']
        self.namespaces[4][u'id'] = [u'Tolololpedia']
        self.namespaces[4][u'es'] = [u'Inciclopedia']
        self.namespaces[4][u'lb'] = [u'Kengencyclopedia']
        self.namespaces[4][u'lo'] = [u'Uncyclopedia']
        self.namespaces[4][u'nn'] = [u'Ikkjepedia']
        self.namespaces[4][u'no'] = [u'Ikkepedia']
        self.namespaces[4][u'zh-tw'] = [u'\u507d\u57fa\u767e\u79d1', u'\u507d\u57fa\u767e\u79d1']
        self.namespaces[4][u'tr'] = [u'Yansiklopedi']
        self.namespaces[4][u'tl'] = [u'Pekepedia']
        self.namespaces[4][u'li'] = [u'Kwatsjpedia']
        self.namespaces[4][u'lv'] = [u'Neciklop\u0113dija']
        self.namespaces[4][u'lt'] = [u'Juokopedij\u0105']
        self.namespaces[4][u'th'] = [u'\u0e44\u0e23\u0e49\u0e2a\u0e32\u0e23\u0e30\u0e19\u0e38\u0e01\u0e23\u0e21']
        self.namespaces[4][u'got'] = [u'Unsaiklopedia']
        self.namespaces[4][u'fo'] = [u'Ikkipedia']
        self.namespaces[4][u'pl'] = [u'Nonsensopedia']
        self.namespaces[4][u'mwl'] = [u'\xc7ciclop\xe9dia']
        self.namespaces[4][u'fr'] = [u'D\xe9sencyclop\xe9die']
        self.namespaces[4][u'hy'] = [u'Angragitaran']
        self.namespaces[4][u'ms'] = [u'Bodohpedia']
        self.namespaces[4][u'hr'] = [u'Neciklopedija']
        self.namespaces[4][u'fy'] = [u'Unsyklopedy']
        self.namespaces[4][u'bn'] = [u'\u0986\u09a8\u09b8\u09be\u0987\u0995\u09cd\u09b2\u09cb\u09aa\u09bf\u09a1\u09bf\u09af\u09bc\u09be']
        self.namespaces[4][u'de'] = [u'Uncyclopedia', u'Stupidedia', u'Kamelopedia']
        self.namespaces[4][u'mg'] = [u'Hatsiklopedia']
        self.namespaces[4][u'da'] = [u'Spademanns Leksikon']
        self.namespaces[4][u'fa'] = [u'\u0646\u0627\u0646\u0634\u0646\u0627\u0645\u0647', u'\u0646\u062f']
        self.namespaces[4][u'bs'] = [u'Neciklopedija']
        self.namespaces[4][u'nl'] = [u'Oncyclopedia']
        self.namespaces[4][u'hu'] = [u'Unciklop\xe9dia']
        self.namespaces[4][u'ja'] = [u'Uncyclopedia']
        self.namespaces[4][u'he'] = [u'\u05d0\u05d9\u05df\u05e6\u05d9\u05e7\u05dc\u05d5\u05e4\u05d3\u05d9\u05d4']
        self.namespaces[4][u'ka'] = [u'Anciklopedia']
        self.namespaces[4][u'ro'] = [u'Neciclopedie']
        self.namespaces[4][u'sr'] = [u'\u041d\u0435\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0438\u0458\u0430']
        self.namespaces[4][u'mo'] = [u'Neciclopedia']
        self.namespaces[4][u'la'] = [u'Necyclopaedia']
        self.namespaces[4][u'ko'] = [u'\ubc31\uad34\uc0ac\uc804', u'\uad34']
        self.namespaces[4][u'sv'] = [u'Psyklopedin']
        self.namespaces[4][u'mk'] = [u'\u041d\u0435\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0438\u0439']
        self.namespaces[4][u'sk'] = [u'Necyklop\xe9dia']
        self.namespaces[4][u'uk'] = [u'\u0406\u043d\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0456\u044f']
        self.namespaces[4][u'sl'] = [u'Butalopedija']
        self.namespaces[4][u'tlh'] = [u"ghItlh'a'pedia"]
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5][u'el'] = [u'\u03a6\u03c1\u03b9\u03ba\u03b7\u03c0\u03b1\u03af\u03b4\u03b5\u03b9\u03b1 \u03c3\u03c5\u03b6\u03ae\u03c4\u03b7\u03c3\u03b7']
        self.namespaces[5][u'sco'] = [u'Scotypedia talk']
        self.namespaces[5][u'en'] = [u'Uncyclopedia talk']
        self.namespaces[5][u'zh'] = [u'\u4f2a\u57fa\u767e\u79d1 talk']
        self.namespaces[5][u'io'] = [u'Neciklopedio Debato']
        self.namespaces[5][u'af'] = [u'Niesiklopediabespreking']
        self.namespaces[5][u'simple'] = [u'Uncyclopedia talk']
        self.namespaces[5][u'oc'] = [u'Discussion Oisquipedia']
        self.namespaces[5][u'is'] = [u'Ekkipediaspjall']
        self.namespaces[5][u'it'] = [u'Discussioni Nonciclopedia']
        self.namespaces[5][u'ar'] = [u'\u0646\u0642\u0627\u0634 \u0628\u064a\u0636\u064a\u067e\u064a\u062f\u064a\u0627']
        self.namespaces[5][u'pt-br'] = [u'Desciclop\xe9dia Discuss\xe3o']
        self.namespaces[5][u'km'] = [u'\u1780\u17b6\u179a\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6\u17a2\u17c6\u1796\u17b8Uncyclopedia', u'Uncyclopedia \u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f']
        self.namespaces[5][u'eo'] = [u'Neciklopedio-Diskuto', u'Neciklopedio diskuto']
        self.namespaces[5][u'fi'] = [u'Keskustelu Hikipediasta']
        self.namespaces[5][u'cs'] = [u'Diskuse k Necyklopedie', u'Necyklopedie diskuse']
        self.namespaces[5][u'et'] = [u'Ebats\xfcklopeedia arutelu']
        self.namespaces[5][u'gl'] = [u'Conversa Desgalipedia']
        self.namespaces[5][u'ie'] = [u'Ninciclopedia Discussion']
        self.namespaces[5][u'id'] = [u'Pembicaraan Tolololpedia']
        self.namespaces[5][u'es'] = [u'Inciclopedia discusi\xf3n']
        self.namespaces[5][u'lb'] = [u'Kengencyclopedia Diskussioun']
        self.namespaces[5][u'lo'] = [u'\u0eaa\u0ebb\u0e99\u0e97\u0eb0\u0e99\u0eb2\u0e81\u0ec8\u0ebd\u0ea7\u0e81\u0eb1\u0e9aUncyclopedia']
        self.namespaces[5][u'nn'] = [u'Ikkjepedia-diskusjon']
        self.namespaces[5][u'no'] = [u'Ikkepedia-diskusjon']
        self.namespaces[5][u'zh-tw'] = [u'\u507d\u57fa\u767e\u79d1\u8a0e\u8ad6', u'\u507d\u57fa\u767e\u79d1\u8a0e\u8ad6']
        self.namespaces[5][u'tr'] = [u'Yansiklopedi tart\u0131\u015fma']
        self.namespaces[5][u'tl'] = [u'Usapang Pekepedia']
        self.namespaces[5][u'li'] = [u'Euverl\xe8k Kwatsjpedia']
        self.namespaces[5][u'lv'] = [u'Neciklop\u0113dija diskusija']
        self.namespaces[5][u'lt'] = [u'Juokopedij\u0105 aptarimas']
        self.namespaces[5][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e2a\u0e32\u0e23\u0e30\u0e19\u0e38\u0e01\u0e23\u0e21']
        self.namespaces[5][u'got'] = [u'Unsaiklopedia talk']
        self.namespaces[5][u'fo'] = [u'Ikkipedia-kjak', u'Ikkipedia kjak']
        self.namespaces[5][u'pl'] = [u'Dyskusja Nonsensopedia']
        self.namespaces[5][u'mwl'] = [u'\xc7ciclop\xe9dia cumbersa', u'\xc7ciclop\xe9dia Discuss\xe3o']
        self.namespaces[5][u'fr'] = [u'Discussion D\xe9sencyclop\xe9die']
        self.namespaces[5][u'hy'] = [u'Angragitaran \u0584\u0576\u0576\u0561\u0580\u056f\u0578\u0582\u0574']
        self.namespaces[5][u'ms'] = [u'Perbincangan Bodohpedia', u'Perbualan Bodohpedia']
        self.namespaces[5][u'hr'] = [u'Razgovor Neciklopedija']
        self.namespaces[5][u'fy'] = [u'Unsyklopedy oerlis']
        self.namespaces[5][u'bn'] = [u'\u0986\u09a8\u09b8\u09be\u0987\u0995\u09cd\u09b2\u09cb\u09aa\u09bf\u09a1\u09bf\u09af\u09bc\u09be \u0986\u09b2\u09cb\u099a\u09a8\u09be', u'\u0986\u09a8\u09b8\u09be\u0987\u0995\u09cd\u09b2\u09cb\u09aa\u09bf\u09a1\u09bf\u09af\u09bc\u09be \u0986\u09b2\u09be\u09aa']
        self.namespaces[5][u'de'] = [u'Uncyclopedia Diskussion', u'Stupidedia Diskussion', u'Kamelopedia Diskussion']
        self.namespaces[5][u'mg'] = [u"Dinika amin'ny Hatsiklopedia", u'Discussion Hatsiklopedia']
        self.namespaces[5][u'da'] = [u'Spademanns Leksikon diskussion', u'Spademanns Leksikon-diskussion']
        self.namespaces[5][u'fa'] = [u'\u0628\u062d\u062b \u0646\u0627\u0646\u0634\u0646\u0627\u0645\u0647']
        self.namespaces[5][u'bs'] = [u'Razgovor s Neciklopedija']
        self.namespaces[5][u'nl'] = [u'Overleg Oncyclopedia']
        self.namespaces[5][u'hu'] = [u'Unciklop\xe9dia-vita', u'Unciklop\xe9dia vita']
        self.namespaces[5][u'ja'] = [u'Uncyclopedia\u30fb\u30c8\u30fc\u30af', u'Uncyclopedia\u2010\u30ce\u30fc\u30c8']
        self.namespaces[5][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05e6\u05d9\u05e7\u05dc\u05d5\u05e4\u05d3\u05d9\u05d4']
        self.namespaces[5][u'ka'] = [u'Anciklopedia \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[5][u'ro'] = [u'Discu\u021bie Neciclopedie', u'Discu\u0163ie Neciclopedie']
        self.namespaces[5][u'sr'] = [u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u043e \u041d\u0435\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0438\u0458\u0430', u'Razgovor o \u041d\u0435\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0438\u0458\u0430']
        self.namespaces[5][u'mo'] = [u'Discu\u021bie Neciclopedia', u'Discu\u0163ie Neciclopedia']
        self.namespaces[5][u'la'] = [u'Disputatio Necyclopaediae']
        self.namespaces[5][u'ko'] = [u'\ubc31\uad34\uc0ac\uc804\ud1a0\ub860', u'\uad34\ud1a0']
        self.namespaces[5][u'sv'] = [u'Psyklopedindiskussion']
        self.namespaces[5][u'mk'] = [u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u0437\u0430 \u041d\u0435\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0438\u0439']
        self.namespaces[5][u'sk'] = [u'Diskusia k Necyklop\xe9dia', u'Koment\xe1r k Wikip\xe9dii']
        self.namespaces[5][u'uk'] = [u'\u041e\u0431\u0433\u043e\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u0406\u043d\u0446\u0438\u043a\u043b\u043e\u043f\u0435\u0434\u0456\u0457']
        self.namespaces[5][u'sl'] = [u'Pogovor o Butalopedija']
        self.namespaces[5][u'tlh'] = [u"ghItlh'a'pedia talk"]
        self.namespaces[6] = self.namespaces.get(6, {})
        self.namespaces[6][u'el'] = [u'Video', u'Image', u'\u0395\u03b9\u03ba\u03cc\u03bd\u03b1']
        self.namespaces[6][u'sco'] = [u'Image']
        self.namespaces[6][u'en'] = [u'Image']
        self.namespaces[6][u'zh'] = [u'Video', u'Image', u'\u56fe\u50cf', u'\u5716\u50cf', u'\u6863\u6848', u'\u6a94\u6848', u'\u6587\u4ef6']
        self.namespaces[6][u'io'] = [u'Image', u'Imajo']
        self.namespaces[6][u'af'] = [u'Image', u'Beeld']
        self.namespaces[6][u'simple'] = [u'Image']
        self.namespaces[6][u'oc'] = [u'Image', u'Imatge']
        self.namespaces[6][u'is'] = [u'Image']
        self.namespaces[6][u'it'] = [u'Video', u'Image', u'Immagine']
        self.namespaces[6][u'ar'] = [u'Video', u'Image', u'\u0635\u0648\u0631\u0629']
        self.namespaces[6][u'pt-br'] = [u'Imagem', u'Image', u'Arquivo', u'Ficheiro']
        self.namespaces[6][u'km'] = [u'Image', u'\u179a\u17bc\u1794\u1797\u17b6\u1796']
        self.namespaces[6][u'eo'] = [u'Video', u'Image']
        self.namespaces[6][u'fi'] = [u'Image', u'Kuva']
        self.namespaces[6][u'cs'] = [u'Video', u'Image']
        self.namespaces[6][u'et'] = [u'Image']
        self.namespaces[6][u'gl'] = [u'Image', u'Imaxe']
        self.namespaces[6][u'ie'] = [u'Image']
        self.namespaces[6][u'id'] = [u'Video', u'Image', u'Gambar']
        self.namespaces[6][u'es'] = [u'Video', u'Image', u'Imagen']
        self.namespaces[6][u'lb'] = [u'Image', u'Bild']
        self.namespaces[6][u'lo'] = [u'Image']
        self.namespaces[6][u'nn'] = [u'Image']
        self.namespaces[6][u'no'] = [u'Image', u'Bilde']
        self.namespaces[6][u'zh-tw'] = [u'\u5716\u50cf', u'Image', u'\u5716\u7247', u'\u6a94\u6848', u'\u5716\u50cf', u'Image', u'\u5716\u7247', u'\u6a94\u6848']
        self.namespaces[6][u'tr'] = [u'Image', u'Resim']
        self.namespaces[6][u'tl'] = [u'Image']
        self.namespaces[6][u'li'] = [u'Image', u'Aafbeilding']
        self.namespaces[6][u'lv'] = [u'Image']
        self.namespaces[6][u'lt'] = [u'Image']
        self.namespaces[6][u'th'] = [u'Image', u'\u0e20\u0e32\u0e1e']
        self.namespaces[6][u'got'] = [u'File', u'Image']
        self.namespaces[6][u'fo'] = [u'Image']
        self.namespaces[6][u'pl'] = [u'Video', u'Image', u'Grafika']
        self.namespaces[6][u'mwl'] = [u'Image', u'Ficheiro']
        self.namespaces[6][u'fr'] = [u'Video', u'Image']
        self.namespaces[6][u'hy'] = [u'Image']
        self.namespaces[6][u'ms'] = [u'Image', u'Imej']
        self.namespaces[6][u'hr'] = [u'Image', u'Slika']
        self.namespaces[6][u'fy'] = [u'Image']
        self.namespaces[6][u'bn'] = [u'Image']
        self.namespaces[6][u'de'] = [u'Video', u'Image', u'Bild', u'Image', u'Bild', u'Image', u'Bild']
        self.namespaces[6][u'mg'] = [u'Image']
        self.namespaces[6][u'da'] = [u'Video', u'Image', u'Billede']
        self.namespaces[6][u'fa'] = [u'Image', u'\u062a\u0635\u0648\u06cc\u0631']
        self.namespaces[6][u'bs'] = [u'Image', u'Slika']
        self.namespaces[6][u'nl'] = [u'Image', u'Afbeelding']
        self.namespaces[6][u'hu'] = [u'Image', u'K\xe9p']
        self.namespaces[6][u'ja'] = [u'Image', u'\u753b\u50cf']
        self.namespaces[6][u'he'] = [u'Video', u'Image', u'\u05ea\u05de\u05d5\u05e0\u05d4']
        self.namespaces[6][u'ka'] = [u'Image', u'\u10e1\u10e3\u10e0\u10d0\u10d7\u10d8']
        self.namespaces[6][u'ro'] = [u'Image', u'Imagine', u'Fi\u015fier']
        self.namespaces[6][u'sr'] = [u'\u0424\u0430\u0458\u043b', u'Image', u'Slika', u'\u0421\u043b\u0438\u043a\u0430']
        self.namespaces[6][u'mo'] = [u'Fi\u0219ier', u'Image', u'Imagine', u'Fi\u015fier']
        self.namespaces[6][u'la'] = [u'Image', u'Imago']
        self.namespaces[6][u'ko'] = [u'Image', u'\uadf8\ub9bc']
        self.namespaces[6][u'sv'] = [u'Image', u'Bild']
        self.namespaces[6][u'mk'] = [u'Image', u'\u0421\u043b\u0438\u043a\u0430']
        self.namespaces[6][u'sk'] = [u'Video', u'Image', u'Obr\xe1zok']
        self.namespaces[6][u'uk'] = [u'Image', u'\u0417\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f']
        self.namespaces[6][u'sl'] = [u'Image']
        self.namespaces[6][u'tlh'] = [u'File', u'Image']
        self.namespaces[7] = self.namespaces.get(7, {})
        self.namespaces[7][u'el'] = [u'Video talk', u'Image talk', u'\u03a3\u03c5\u03b6\u03ae\u03c4\u03b7\u03c3\u03b7 \u03b5\u03b9\u03ba\u03cc\u03bd\u03b1\u03c2']
        self.namespaces[7][u'sco'] = [u'Image talk']
        self.namespaces[7][u'en'] = [u'Image talk']
        self.namespaces[7][u'zh'] = [u'Video talk', u'Image talk', u'\u56fe\u50cf\u5bf9\u8bdd', u'\u5716\u50cf\u5c0d\u8a71', u'\u56fe\u50cf\u8ba8\u8bba', u'\u5716\u50cf\u8a0e\u8ad6', u'\u6863\u6848\u5bf9\u8bdd', u'\u6a94\u6848\u5c0d\u8a71', u'\u6863\u6848\u8ba8\u8bba', u'\u6a94\u6848\u8a0e\u8ad6', u'\u6587\u4ef6\u5bf9\u8bdd', u'\u6587\u4ef6\u5c0d\u8a71', u'\u6587\u4ef6\u8ba8\u8bba', u'\u6587\u4ef6\u8a0e\u8ad6']
        self.namespaces[7][u'io'] = [u'Image talk', u'Imajo Debato']
        self.namespaces[7][u'af'] = [u'Image talk', u'Beeldbespreking']
        self.namespaces[7][u'simple'] = [u'Image talk']
        self.namespaces[7][u'oc'] = [u'Image talk', u'Discutida Imatge', u'Discussion Imatge']
        self.namespaces[7][u'is'] = [u'Image talk']
        self.namespaces[7][u'it'] = [u'Video talk', u'Image talk', u'Discussioni immagine']
        self.namespaces[7][u'ar'] = [u'Video talk', u'Image talk', u'\u0646\u0642\u0627\u0634 \u0627\u0644\u0635\u0648\u0631\u0629']
        self.namespaces[7][u'pt-br'] = [u'Imagem Discuss\xe3o', u'Image talk', u'Arquivo Discuss\xe3o', u'Ficheiro Discuss\xe3o']
        self.namespaces[7][u'km'] = [u'Image talk', u'\u1780\u17b6\u179a\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6\u17a2\u17c6\u1796\u17b8\u179a\u17bc\u1794\u1797\u17b6\u1796', u'\u179a\u17bc\u1794\u1797\u17b6\u1796-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[7][u'eo'] = [u'Video talk', u'Image talk', u'Dosiera diskuto']
        self.namespaces[7][u'fi'] = [u'Image talk', u'Keskustelu kuvasta']
        self.namespaces[7][u'cs'] = [u'Video talk', u'Image talk', u'Soubor diskuse']
        self.namespaces[7][u'et'] = [u'Image talk']
        self.namespaces[7][u'gl'] = [u'Image talk', u'Conversa Imaxe']
        self.namespaces[7][u'ie'] = [u'Image talk']
        self.namespaces[7][u'id'] = [u'Video talk', u'Image talk', u'Gambar Pembicaraan', u'Pembicaraan Gambar']
        self.namespaces[7][u'es'] = [u'Video talk', u'Image talk', u'Imagen Discusi\xf3n']
        self.namespaces[7][u'lb'] = [u'Image talk', u'Bild Diskussioun']
        self.namespaces[7][u'lo'] = [u'Image talk']
        self.namespaces[7][u'nn'] = [u'Image talk']
        self.namespaces[7][u'no'] = [u'Image talk', u'Bildediskusjon']
        self.namespaces[7][u'zh-tw'] = [u'\u5716\u50cf\u8a0e\u8ad6', u'Image talk', u'\u5716\u7247\u8a0e\u8ad6', u'\u6a94\u6848\u8a0e\u8ad6', u'\u5716\u50cf\u8a0e\u8ad6', u'Image talk', u'\u5716\u7247\u8a0e\u8ad6', u'\u6a94\u6848\u8a0e\u8ad6']
        self.namespaces[7][u'tr'] = [u'Image talk', u'Resim tart\u0131\u015fma']
        self.namespaces[7][u'tl'] = [u'Image talk']
        self.namespaces[7][u'li'] = [u'Image talk', u'Euverl\xe8k afbeelding']
        self.namespaces[7][u'lv'] = [u'Image talk']
        self.namespaces[7][u'lt'] = [u'Image talk']
        self.namespaces[7][u'th'] = [u'Image talk', u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e20\u0e32\u0e1e']
        self.namespaces[7][u'got'] = [u'File talk', u'Image talk']
        self.namespaces[7][u'fo'] = [u'Image talk', u'Mynd kjak']
        self.namespaces[7][u'pl'] = [u'Video talk', u'Image talk', u'Dyskusja grafiki']
        self.namespaces[7][u'mwl'] = [u'Image talk', u'Ficheiro Discuss\xe3o', u'Imagem Discuss\xe3o']
        self.namespaces[7][u'fr'] = [u'Video talk', u'Image talk', u'Discussion Fichier', u'Discussion Image']
        self.namespaces[7][u'hy'] = [u'Image talk']
        self.namespaces[7][u'ms'] = [u'Image talk', u'Perbincangan Imej', u'Imej Perbualan']
        self.namespaces[7][u'hr'] = [u'Image talk', u'Razgovor o slici']
        self.namespaces[7][u'fy'] = [u'Image talk']
        self.namespaces[7][u'bn'] = [u'Image talk', u'\u099a\u09bf\u09a4\u09cd\u09b0 \u0986\u09b2\u09be\u09aa', u'MediaWiki \u0986\u09b2\u09be\u09aa']
        self.namespaces[7][u'de'] = [u'Video talk', u'Image talk', u'Bild Diskussion', u'Image talk', u'Bild Diskussion', u'Image talk', u'Bild Diskussion']
        self.namespaces[7][u'mg'] = [u'Image talk', u'Discussion Image']
        self.namespaces[7][u'da'] = [u'Video talk', u'Image talk', u'Billeddiskussion']
        self.namespaces[7][u'fa'] = [u'Image talk', u'\u0628\u062d\u062b \u062a\u0635\u0648\u06cc\u0631']
        self.namespaces[7][u'bs'] = [u'Image talk']
        self.namespaces[7][u'nl'] = [u'Image talk', u'Overleg afbeelding']
        self.namespaces[7][u'hu'] = [u'Image talk', u'K\xe9pvita', u'K\xe9p vita']
        self.namespaces[7][u'ja'] = [u'Image talk', u'\u753b\u50cf\u2010\u30ce\u30fc\u30c8', u'\u30d5\u30a1\u30a4\u30eb\u2010\u30ce\u30fc\u30c8']
        self.namespaces[7][u'he'] = [u'Video talk', u'Image talk', u'\u05e9\u05d9\u05d7\u05ea \u05ea\u05de\u05d5\u05e0\u05d4']
        self.namespaces[7][u'ka'] = [u'Image talk', u'\u10e1\u10e3\u10e0\u10d0\u10d7\u10d8 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[7][u'ro'] = [u'Image talk', u'Discu\u0163ie Imagine', u'Discu\u0163ie Fi\u015fier']
        self.namespaces[7][u'sr'] = [u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u043e \u0444\u0430\u0458\u043b\u0443', u'Image talk', u'Razgovor o slici', u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u043e \u0441\u043b\u0438\u0446\u0438']
        self.namespaces[7][u'mo'] = [u'Discu\u021bie Fi\u0219ier', u'Image talk', u'Discu\u0163ie Imagine', u'Discu\u0163ie Fi\u015fier']
        self.namespaces[7][u'la'] = [u'Image talk', u'Disputatio Imaginis']
        self.namespaces[7][u'ko'] = [u'Image talk']
        self.namespaces[7][u'sv'] = [u'Image talk', u'Bilddiskussion']
        self.namespaces[7][u'mk'] = [u'Image talk', u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u0437\u0430 \u0441\u043b\u0438\u043a\u0430']
        self.namespaces[7][u'sk'] = [u'Video talk', u'Image talk', u'Diskusia k obr\xe1zku', u'Koment\xe1r k obr\xe1zku']
        self.namespaces[7][u'uk'] = [u'Image talk', u'\u041e\u0431\u0433\u043e\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u043d\u044f']
        self.namespaces[7][u'sl'] = [u'Image talk']
        self.namespaces[7][u'tlh'] = [u'File talk', u'Image talk']
        self.namespaces[8] = self.namespaces.get(8, {})
        self.namespaces[8][u'eo'] = [u'MediaVikio']
        self.namespaces[8][u'zh-tw'] = [u'\u5a92\u9ad4\u507d\u57fa', u'\u5a92\u9ad4\u507d\u57fa']
        self.namespaces[8][u'bs'] = [u'MedijaViki']
        self.namespaces[8][u'oc'] = [u'Media\xf2iqui']
        self.namespaces[8][u'km'] = [u'\u1798\u17b8\u178c\u17b6\u179c\u17b7\u1782\u17b8']
        self.namespaces[8][u'tr'] = [u'MedyaViki']
        self.namespaces[8][u'sr'] = [u'\u041c\u0435\u0434\u0438\u0458\u0430\u0412\u0438\u043a\u0438', u'MedijaViki']
        self.namespaces[8][u'fo'] = [u'MidiaWiki']
        self.namespaces[9] = self.namespaces.get(9, {})
        self.namespaces[9][u'eo'] = [u'MediaWiki diskuto', u'MediaVikia diskuto']
        self.namespaces[9][u'ko'] = [u'MediaWiki\ud1a0\ub860']
        self.namespaces[9][u'pt-br'] = [u'MediaWiki Discuss\xe3o']
        self.namespaces[9][u'cs'] = [u'MediaWiki diskuse']
        self.namespaces[9][u'id'] = [u'MediaWiki Pembicaraan']
        self.namespaces[9][u'zh-tw'] = [u'\u5a92\u9ad4\u507d\u57fa\u8a0e\u8ad6', u'\u5a92\u9ad4\u507d\u57fa\u8a0e\u8ad6']
        self.namespaces[9][u'tr'] = [u'MedyaViki tart\u0131\u015fma']
        self.namespaces[9][u'ro'] = [u'Discu\u0163ie MediaWiki']
        self.namespaces[9][u'mwl'] = [u'MediaWiki Discuss\xe3o']
        self.namespaces[9][u'mg'] = [u'Discussion MediaWiki']
        self.namespaces[9][u'da'] = [u'MediaWiki diskussion']
        self.namespaces[9][u'bs'] = [u'Razgovor o MedijaVikiju']
        self.namespaces[9][u'hu'] = [u'MediaWiki vita']
        self.namespaces[9][u'ja'] = [u'MediaWiki\u2010\u30ce\u30fc\u30c8']
        self.namespaces[9][u'fo'] = [u'MidiaWiki kjak']
        self.namespaces[9][u'ka'] = [u'\u10db\u10d4\u10d3\u10d8\u10d0\u10d5\u10d8\u10d9\u10d8 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[9][u'sr'] = [u'\u0420\u0430\u0437\u0433\u043e\u0432\u043e\u0440 \u043e \u041c\u0435\u0434\u0438\u0458\u0430\u0412\u0438\u043a\u0438\u0458\u0443', u'Razgovor o MedijaVikiju']
        self.namespaces[9][u'mo'] = [u'Discu\u021bie MediaWiki', u'Discu\u0163ie MediaWiki']
        self.namespaces[9][u'oc'] = [u'Discussion Media\xf2iqui', u'Discutida Media\xf2iqui']
        self.namespaces[9][u'sv'] = [u'MediaWiki diskussion']
        self.namespaces[9][u'km'] = [u'\u1798\u17b8\u178c\u17b6\u179c\u17b7\u1782\u17b8-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[9][u'sk'] = [u'Koment\xe1r k MediaWiki']
        self.namespaces[9][u'ms'] = [u'MediaWiki Perbualan']
        self.namespaces[9][u'tlh'] = [u'MediaWiki talk']
        self.namespaces[10] = self.namespaces.get(10, {})
        self.namespaces[10][u'mg'] = [u'Mod\xe8le']
        self.namespaces[10][u'zh'] = [u'\u6a21\u677f', u'\u6837\u677f', u'\u6a23\u677f']
        self.namespaces[10][u'zh-tw'] = [u'\u6a21\u677f', u'\u7bc4\u672c', u'\u6a21\u677f', u'\u7bc4\u672c']
        self.namespaces[10][u'mo'] = [u'Format']
        self.namespaces[10][u'tl'] = [u'Suleras']
        self.namespaces[10][u'pt-br'] = [u'Predefini\xe7\xe3o']
        self.namespaces[10][u'io'] = [u'Modelo']
        self.namespaces[10][u'sr'] = [u'\u0160ablon']
        self.namespaces[10][u'got'] = [u'Template']
        self.namespaces[10][u'tlh'] = [u'Template']
        self.namespaces[10][u'mwl'] = [u'Predefini\xe7\xe3o']
        self.namespaces[11] = self.namespaces.get(11, {})
        self.namespaces[11][u'eo'] = [u'\u015cablona diskuto']
        self.namespaces[11][u'zh'] = [u'\u6a21\u677f\u5bf9\u8bdd', u'\u6a21\u677f\u5c0d\u8a71', u'\u6a21\u677f\u8ba8\u8bba', u'\u6a21\u677f\u8a0e\u8ad6', u'\u6837\u677f\u5bf9\u8bdd', u'\u6a23\u677f\u5c0d\u8a71', u'\u6837\u677f\u8ba8\u8bba', u'\u6a23\u677f\u8a0e\u8ad6']
        self.namespaces[11][u'pt-br'] = [u'Predefini\xe7\xe3o Discuss\xe3o']
        self.namespaces[11][u'io'] = [u'Modelo Debato']
        self.namespaces[11][u'cs'] = [u'\u0160ablona diskuse']
        self.namespaces[11][u'gl'] = [u'Conversa Modelo']
        self.namespaces[11][u'id'] = [u'Templat Pembicaraan']
        self.namespaces[11][u'zh-tw'] = [u'\u6a21\u677f\u8a0e\u8ad6', u'\u7bc4\u672c\u8a0e\u8ad6', u'\u6a21\u677f\u8a0e\u8ad6', u'\u7bc4\u672c\u8a0e\u8ad6']
        self.namespaces[11][u'tl'] = [u'Usapang suleras']
        self.namespaces[11][u'got'] = [u'Template talk']
        self.namespaces[11][u'ro'] = [u'Discu\u0163ie Format']
        self.namespaces[11][u'mwl'] = [u'Predefini\xe7\xe3o Discuss\xe3o']
        self.namespaces[11][u'fr'] = [u'Discussion Mod\xe8le']
        self.namespaces[11][u'uk'] = [u'\u041e\u0431\u0433\u043e\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u0448\u0430\u0431\u043b\u043e\u043d\u0430']
        self.namespaces[11][u'mg'] = [u'Discussion Mod\xe8le']
        self.namespaces[11][u'hu'] = [u'Sablon vita']
        self.namespaces[11][u'ja'] = [u'Template\u2010\u30ce\u30fc\u30c8']
        self.namespaces[11][u'fo'] = [u'Fyrimynd kjak']
        self.namespaces[11][u'ka'] = [u'\u10d7\u10d0\u10e0\u10d2\u10d8 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[11][u'sr'] = [u'Razgovor o \u0161ablonu']
        self.namespaces[11][u'mo'] = [u'Discu\u021bie Format', u'Discu\u0163ie Format']
        self.namespaces[11][u'oc'] = [u'Discutida Mod\xe8l']
        self.namespaces[11][u'km'] = [u'\u1791\u17c6\u1796\u17d0\u179a\u1782\u17c6\u179a\u17bc-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[11][u'ms'] = [u'Perbualan Templat']
        self.namespaces[11][u'tlh'] = [u'Template talk']
        self.namespaces[12] = self.namespaces.get(12, {})
        self.namespaces[12][u'mg'] = [u'Aide', u'Fanampiana']
        self.namespaces[12][u'zh'] = [u'\u5e2e\u52a9', u'\u5e6b\u52a9']
        self.namespaces[12][u'zh-tw'] = [u'\u5354\u52a9', u'\u4f7f\u7528\u8aaa\u660e', u'\u5354\u52a9', u'\u4f7f\u7528\u8aaa\u660e']
        self.namespaces[12][u'mo'] = [u'Ajutor']
        self.namespaces[12][u'pt-br'] = [u'Ajuda']
        self.namespaces[12][u'sr'] = [u'Pomo\u0107']
        self.namespaces[12][u'got'] = [u'Help']
        self.namespaces[12][u'tlh'] = [u'Help']
        self.namespaces[12][u'he'] = [u'\u05de\u05d3\u05e8\u05d9\u05da']
        self.namespaces[13] = self.namespaces.get(13, {})
        self.namespaces[13][u'eo'] = [u'Helpa diskuto']
        self.namespaces[13][u'zh'] = [u'\u5e2e\u52a9\u5bf9\u8bdd', u'\u5e6b\u52a9\u5c0d\u8a71', u'\u5e2e\u52a9\u8ba8\u8bba', u'\u5e6b\u52a9\u8a0e\u8ad6']
        self.namespaces[13][u'pt-br'] = [u'Ajuda Discuss\xe3o']
        self.namespaces[13][u'cs'] = [u'N\xe1pov\u011bda diskuse']
        self.namespaces[13][u'gl'] = [u'Conversa Axuda']
        self.namespaces[13][u'id'] = [u'Bantuan Pembicaraan']
        self.namespaces[13][u'zh-tw'] = [u'\u5354\u52a9\u8a0e\u8ad6', u'\u4f7f\u7528\u8aaa\u660e\u8a0e\u8ad6', u'\u5354\u52a9\u8a0e\u8ad6', u'\u4f7f\u7528\u8aaa\u660e\u8a0e\u8ad6']
        self.namespaces[13][u'fo'] = [u'Hj\xe1lp kjak']
        self.namespaces[13][u'got'] = [u'Help talk']
        self.namespaces[13][u'ro'] = [u'Discu\u0163ie Ajutor']
        self.namespaces[13][u'mwl'] = [u'Ajuda Discuss\xe3o']
        self.namespaces[13][u'fr'] = [u'Discussion Aide']
        self.namespaces[13][u'mg'] = [u'Discussion Aide', u"Dinika amin'ny fanampiana"]
        self.namespaces[13][u'da'] = [u'Hj\xe6lp diskussion']
        self.namespaces[13][u'hu'] = [u'Seg\xedts\xe9g vita']
        self.namespaces[13][u'ja'] = [u'Help\u2010\u30ce\u30fc\u30c8']
        self.namespaces[13][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05de\u05d3\u05e8\u05d9\u05da']
        self.namespaces[13][u'ka'] = [u'\u10d3\u10d0\u10ee\u10db\u10d0\u10e0\u10d4\u10d1\u10d0 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[13][u'sr'] = [u'Razgovor o pomo\u0107i']
        self.namespaces[13][u'mo'] = [u'Discu\u021bie Ajutor', u'Discu\u0163ie Ajutor']
        self.namespaces[13][u'oc'] = [u'Discutida Ajuda']
        self.namespaces[13][u'sv'] = [u'Hj\xe4lp diskussion']
        self.namespaces[13][u'km'] = [u'\u1787\u17c6\u1793\u17bd\u1799-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6']
        self.namespaces[13][u'ms'] = [u'Perbualan Bantuan']
        self.namespaces[13][u'tlh'] = [u'Help talk']
        self.namespaces[14] = self.namespaces.get(14, {})
        self.namespaces[14][u'mg'] = [u'Cat\xe9gorie']
        self.namespaces[14][u'zh'] = [u'\u5206\u7c7b', u'\u5206\u985e']
        self.namespaces[14][u'zh-tw'] = [u'\u5206\u985e', u'\u5206\u985e']
        self.namespaces[14][u'mo'] = [u'Categorie']
        self.namespaces[14][u'km'] = [u'\u1785\u17c6\u178e\u17b6\u178f\u17cb\u1780\u17d2\u179a\u17bb\u1798', u'\u1785\u17c6\u1793\u17b6\u178f\u17cb\u1790\u17d2\u1793\u17b6\u1780\u17cb\u1780\u17d2\u179a\u17bb\u1798']
        self.namespaces[14][u'li'] = [u'Kategorie']
        self.namespaces[14][u'tl'] = [u'Kaurian']
        self.namespaces[14][u'pt-br'] = [u'Categoria']
        self.namespaces[14][u'sr'] = [u'Kategorija']
        self.namespaces[14][u'got'] = [u'Category']
        self.namespaces[14][u'tlh'] = [u'Category']
        self.namespaces[14][u'mwl'] = [u'Categoria']
        self.namespaces[15] = self.namespaces.get(15, {})
        self.namespaces[15][u'eo'] = [u'Kategoria diskuto']
        self.namespaces[15][u'zh'] = [u'\u5206\u7c7b\u5bf9\u8bdd', u'\u5206\u985e\u5c0d\u8a71', u'\u5206\u7c7b\u8ba8\u8bba', u'\u5206\u985e\u8a0e\u8ad6']
        self.namespaces[15][u'pt-br'] = [u'Categoria Discuss\xe3o']
        self.namespaces[15][u'cs'] = [u'Kategorie diskuse']
        self.namespaces[15][u'gl'] = [u'Conversa Categor\xeda']
        self.namespaces[15][u'id'] = [u'Kategori Pembicaraan']
        self.namespaces[15][u'zh-tw'] = [u'\u5206\u985e\u8a0e\u8ad6', u'\u5206\u985e\u8a0e\u8ad6']
        self.namespaces[15][u'li'] = [u'Euverl\xe8k kategorie']
        self.namespaces[15][u'tl'] = [u'Usapang kaurian']
        self.namespaces[15][u'got'] = [u'Category talk']
        self.namespaces[15][u'ro'] = [u'Discu\u0163ie Categorie']
        self.namespaces[15][u'mwl'] = [u'Categoria Discuss\xe3o']
        self.namespaces[15][u'fr'] = [u'Discussion Cat\xe9gorie']
        self.namespaces[15][u'mg'] = [u'Discussion Cat\xe9gorie']
        self.namespaces[15][u'hu'] = [u'Kateg\xf3ria vita']
        self.namespaces[15][u'ja'] = [u'Category\u2010\u30ce\u30fc\u30c8']
        self.namespaces[15][u'fo'] = [u'B\xf3lkur kjak']
        self.namespaces[15][u'ka'] = [u'\u10d9\u10d0\u10e2\u10d4\u10d2\u10dd\u10e0\u10d8\u10d0 \u10d2\u10d0\u10dc\u10ee\u10d8\u10da\u10d5\u10d0']
        self.namespaces[15][u'sr'] = [u'Razgovor o kategoriji']
        self.namespaces[15][u'mo'] = [u'Discu\u021bie Categorie', u'Discu\u0163ie Categorie']
        self.namespaces[15][u'oc'] = [u'Discutida Categoria']
        self.namespaces[15][u'km'] = [u'\u1785\u17c6\u178e\u17b6\u178f\u17cb\u1780\u17d2\u179a\u17bb\u1798-\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6', u'\u1780\u17b6\u179a\u1796\u17b7\u1797\u17b6\u1780\u17d2\u179f\u17b6\u17a2\u17c6\u1796\u17b8\u1785\u17c6\u1793\u17b6\u178f\u17cb\u1790\u17d2\u1793\u17b6\u1780\u17cb\u1780\u17d2\u179a\u17bb\u1798']
        self.namespaces[15][u'ms'] = [u'Perbualan Kategori']
        self.namespaces[15][u'tlh'] = [u'Category talk']
        self.namespaces[16] = self.namespaces.get(16, {})
        self.namespaces[16][u'simple'] = [u'HowTo']
        self.namespaces[16][u'zh-tw'] = [u'\u507d\u57fa\u65b0\u805e', u'\u507d\u57fa\u65b0\u805e']
        self.namespaces[16][u'mo'] = [u'Nec\u0163ionar']
        self.namespaces[16][u'nl'] = [u'Portaal']
        self.namespaces[16][u'th'] = [u'\u0e2d\u0e31\u0e19\u0e44\u0e0b\u0e42\u0e04\u0e25\u0e1e\u0e35\u0e40\u0e14\u0e35\u0e22']
        self.namespaces[17] = self.namespaces.get(17, {})
        self.namespaces[17][u'simple'] = [u'HowTo talk']
        self.namespaces[17][u'zh-tw'] = [u'\u507d\u57fa\u65b0\u805e\u8a0e\u8ad6', u'\u507d\u57fa\u65b0\u805e\u8a0e\u8ad6']
        self.namespaces[17][u'mo'] = [u'Discu\u021bie Nec\u0163ionar']
        self.namespaces[17][u'nl'] = [u'Overleg portaal']
        self.namespaces[17][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e2d\u0e31\u0e19\u0e44\u0e0b\u0e42\u0e04\u0e25\u0e1e\u0e35\u0e40\u0e14\u0e35\u0e22']
        self.namespaces[18] = self.namespaces.get(18, {})
        self.namespaces[18][u'nl'] = [u'OnNieuws']
        self.namespaces[18][u'simple'] = [u'Undex']
        self.namespaces[18][u'zh-tw'] = [u'\u507d\u57fa\u8fad\u5178', u'\u507d\u57fa\u8a5e\u5178', u'\u507d\u57fa\u8fad\u5178', u'\u507d\u57fa\u8a5e\u5178']
        self.namespaces[18][u'mo'] = [u'Uichicitati']
        self.namespaces[18][u'pt-br'] = [u'Fatos']
        self.namespaces[18][u'th'] = [u'\u0e44\u0e23\u0e49\u0e02\u0e48\u0e32\u0e27']
        self.namespaces[18][u'fi'] = [u'Hikinews']
        self.namespaces[18][u'got'] = [u'\U00010330\U00010342\U0001033c\U00010330\U00010339\U00010349']
        self.namespaces[19] = self.namespaces.get(19, {})
        self.namespaces[19][u'nl'] = [u'Overleg OnNieuws']
        self.namespaces[19][u'simple'] = [u'Undex talk']
        self.namespaces[19][u'zh-tw'] = [u'\u507d\u57fa\u8fad\u5178\u8a0e\u8ad6', u'\u507d\u57fa\u8a5e\u5178\u8a0e\u8ad6', u'\u507d\u57fa\u8fad\u5178\u8a0e\u8ad6', u'\u507d\u57fa\u8a5e\u5178\u8a0e\u8ad6']
        self.namespaces[19][u'mo'] = [u'Discu\u021bie Uichicitati']
        self.namespaces[19][u'pt-br'] = [u'Fatos Discuss\xe3o']
        self.namespaces[19][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e02\u0e48\u0e32\u0e27']
        self.namespaces[19][u'fi'] = [u'Keskustelu Hikinewseist\xe4']
        self.namespaces[19][u'got'] = [u'\U00010330\U00010342\U0001033c\U00010330\U00010339\U00010349 \U00010332\U00010330\U00010345\U00010330\U0001033f\U00010342\U00010333\U0001033e\U00010330']
        self.namespaces[20] = self.namespaces.get(20, {})
        self.namespaces[20][u'nl'] = [u'Onwoordenboek']
        self.namespaces[20][u'simple'] = [u'Userbox']
        self.namespaces[20][u'zh-tw'] = [u'\u52d5\u6f2b\u904a\u6232', u'\u507d\u57fa\u904a\u6232', u'Ungame', u'\u52d5\u6f2b\u904a\u6232', u'\u507d\u57fa\u904a\u6232', u'Ungame']
        self.namespaces[20][u'th'] = [u'\u0e44\u0e23\u0e49\u0e27\u0e34\u0e17\u0e22\u0e32\u0e25\u0e31\u0e22']
        self.namespaces[20][u'got'] = [u'\U00010346\U00010330\U00010339\U00010330\U0001033d\U00010345\U00010330\U00010342\U00010333\U00010330\U00010331\U00010349\U0001033a\U00010330']
        self.namespaces[20][u'fi'] = [u'Hiktionary']
        self.namespaces[21] = self.namespaces.get(21, {})
        self.namespaces[21][u'nl'] = [u'Overleg Onwoordenboek']
        self.namespaces[21][u'simple'] = [u'Userbox talk']
        self.namespaces[21][u'zh-tw'] = [u'\u52d5\u6f2b\u904a\u6232\u8a0e\u8ad6', u'Ungame talk', u'\u507d\u57fa\u904a\u6232\u8a0e\u8ad6', u'\u52d5\u6f2b\u904a\u6232\u8a0e\u8ad6', u'Ungame talk', u'\u507d\u57fa\u904a\u6232\u8a0e\u8ad6']
        self.namespaces[21][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e27\u0e34\u0e17\u0e22\u0e32\u0e25\u0e31\u0e22']
        self.namespaces[21][u'got'] = [u'\U00010346\U00010330\U00010339\U00010330\U0001033d\U00010345\U00010330\U00010342\U00010333\U00010330\U00010331\U00010349\U0001033a\U00010330 \U00010332\U00010330\U00010345\U00010330\U0001033f\U00010342\U00010333\U0001033e\U00010330']
        self.namespaces[21][u'fi'] = [u'Keskustelu Hiktionarysta']
        self.namespaces[22] = self.namespaces.get(22, {})
        self.namespaces[22][u'nl'] = [u'OnBoeken']
        self.namespaces[22][u'simple'] = [u'Disambiguation']
        self.namespaces[22][u'zh-tw'] = [u'\u507d\u57fa\u6587\u5eab', u'\u507d\u57fa\u6587\u5eab']
        self.namespaces[22][u'pt-br'] = [u'Descita\xe7\xf5es']
        self.namespaces[22][u'th'] = [u'\u0e44\u0e23\u0e49\u0e1e\u0e08\u0e19\u0e32\u0e19\u0e38\u0e01\u0e23\u0e21']
        self.namespaces[22][u'fi'] = [u'Hikikirjasto']
        self.namespaces[23] = self.namespaces.get(23, {})
        self.namespaces[23][u'nl'] = [u'Overleg OnBoeken']
        self.namespaces[23][u'simple'] = [u'Disambiguation talk']
        self.namespaces[23][u'zh-tw'] = [u'\u507d\u57fa\u6587\u5eab\u8a0e\u8ad6', u'\u507d\u57fa\u6587\u5eab\u8a0e\u8ad6']
        self.namespaces[23][u'pt-br'] = [u'Descita\xe7\xf5es Discuss\xe3o']
        self.namespaces[23][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e1e\u0e08\u0e19\u0e32\u0e19\u0e38\u0e01\u0e23\u0e21']
        self.namespaces[23][u'fi'] = [u'Keskustelu hikikirjasta']
        self.namespaces[24] = self.namespaces.get(24, {})
        self.namespaces[24][u'zh-tw'] = [u'\u4e3b\u984c\u5c55\u9928', u'Portal', u'\u5165\u53e3', u'\u4e3b\u984c\u5c55\u9928', u'Portal', u'\u5165\u53e3']
        self.namespaces[24][u'th'] = [u'\u0e44\u0e23\u0e49\u0e0a\u0e35\u0e27\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34']
        self.namespaces[24][u'fi'] = [u'Hikisitaatit']
        self.namespaces[25] = self.namespaces.get(25, {})
        self.namespaces[25][u'zh-tw'] = [u'\u4e3b\u984c\u5c55\u9928\u8a0e\u8ad6', u'Portal talk', u'\u5165\u53e3\u8a0e\u8ad6', u'\u4e3b\u984c\u5c55\u9928\u8a0e\u8ad6', u'Portal talk', u'\u5165\u53e3\u8a0e\u8ad6']
        self.namespaces[25][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e0a\u0e35\u0e27\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34']
        self.namespaces[25][u'fi'] = [u'Keskustelu hikisitaatista']
        self.namespaces[26] = self.namespaces.get(26, {})
        self.namespaces[26][u'simple'] = [u'UnNews']
        self.namespaces[26][u'ro'] = [u'Necimanuale']
        self.namespaces[26][u'nl'] = [u'OnZinnen']
        self.namespaces[26][u'th'] = [u'\u0e2a\u0e20\u0e32\u0e19\u0e49\u0e33\u0e0a\u0e32']
        self.namespaces[27] = self.namespaces.get(27, {})
        self.namespaces[27][u'simple'] = [u'UnNews talk']
        self.namespaces[27][u'ro'] = [u'Discu\u021bie Necimanuale']
        self.namespaces[27][u'nl'] = [u'Overleg OnZinnen']
        self.namespaces[27][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e2a\u0e20\u0e32\u0e19\u0e49\u0e33\u0e0a\u0e32']
        self.namespaces[28] = self.namespaces.get(28, {})
        self.namespaces[28][u'simple'] = [u'UnBooks']
        self.namespaces[28][u'zh-tw'] = [u'\u8a5e\u610f\u5206\u9053', u'R', u'\u8a5e\u610f\u5206\u9053', u'R']
        self.namespaces[28][u'nl'] = [u'Ongerijmd']
        self.namespaces[28][u'th'] = [u'\u0e1a\u0e2d\u0e23\u0e4c\u0e14']
        self.namespaces[28][u'fi'] = [u'Hikipeli']
        self.namespaces[29] = self.namespaces.get(29, {})
        self.namespaces[29][u'simple'] = [u'UnBooks talk']
        self.namespaces[29][u'zh-tw'] = [u'\u8a5e\u610f\u5206\u9053\u8a0e\u8ad6', u'\u8a5e\u610f\u5206\u9053\u8a0e\u8ad6']
        self.namespaces[29][u'nl'] = [u'Overleg Ongerijmd']
        self.namespaces[29][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e1a\u0e2d\u0e23\u0e4c\u0e14']
        self.namespaces[29][u'fi'] = [u'Hihitys Hikipelist\xe4', u'Hihitys hikipelist\xe4']
        self.namespaces[30] = self.namespaces.get(30, {})
        self.namespaces[30][u'nl'] = [u'Oncycloversiteit']
        self.namespaces[30][u'simple'] = [u'UnDictionary']
        self.namespaces[30][u'zh-tw'] = [u'\u81fa\u8a9e', u'F', u'\u53f0\u8a9e', u'\u81fa\u8a9e', u'F', u'\u53f0\u8a9e']
        self.namespaces[30][u'pt-br'] = [u'Deslivros', u'Desmanual', u'Desmanuais']
        self.namespaces[30][u'th'] = [u'\u0e44\u0e23\u0e49\u0e0b\u0e2d\u0e23\u0e4c\u0e0b']
        self.namespaces[30][u'fi'] = [u'Hikiopisto']
        self.namespaces[30][u'ro'] = [u'Necik\u0163ionar']
        self.namespaces[31] = self.namespaces.get(31, {})
        self.namespaces[31][u'nl'] = [u'Overleg Oncycloversiteit']
        self.namespaces[31][u'simple'] = [u'UnDictionary talk']
        self.namespaces[31][u'zh-tw'] = [u'\u81fa\u8a9e\u8a0e\u8ad6', u'\u53f0\u8a9e\u8a0e\u8ad6', u'\u81fa\u8a9e\u8a0e\u8ad6', u'\u53f0\u8a9e\u8a0e\u8ad6']
        self.namespaces[31][u'pt-br'] = [u'Deslivros Discuss\xe3o']
        self.namespaces[31][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e0b\u0e2d\u0e23\u0e4c\u0e0b']
        self.namespaces[31][u'fi'] = [u'Keskustelu hikikurssista']
        self.namespaces[31][u'ro'] = [u'Discu\u021bie Necik\u0163ionar']
        self.namespaces[32] = self.namespaces.get(32, {})
        self.namespaces[32][u'simple'] = [u'Why?']
        self.namespaces[32][u'zh-tw'] = [u'\u9999\u6e2f\u8a9e', u'H', u'\u9999\u6e2f\u8a9e', u'H']
        self.namespaces[32][u'pt-br'] = [u'Desentrevistas']
        self.namespaces[32][u'th'] = [u'\u0e44\u0e23\u0e49\u0e04\u0e33\u0e04\u0e21']
        self.namespaces[32][u'fi'] = [u'Hikiaineisto']
        self.namespaces[32][u'ro'] = [u'Necicitat']
        self.namespaces[32][u'ja'] = [u'Portal']
        self.namespaces[33] = self.namespaces.get(33, {})
        self.namespaces[33][u'simple'] = [u'Why? talk']
        self.namespaces[33][u'zh-tw'] = [u'\u9999\u6e2f\u8a9e\u8a0e\u8ad6', u'\u9999\u6e2f\u8a9e\u8a0e\u8ad6']
        self.namespaces[33][u'pt-br'] = [u'Desentrevistas Discuss\xe3o']
        self.namespaces[33][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e04\u0e33\u0e04\u0e21']
        self.namespaces[33][u'fi'] = [u'Keskustelu hikiaineistosta']
        self.namespaces[33][u'ro'] = [u'Discu\u021bie Necicitat']
        self.namespaces[33][u'ja'] = [u'Portal talk']
        self.namespaces[34] = self.namespaces.get(34, {})
        self.namespaces[34][u'pt-br'] = [u'Despoesias']
        self.namespaces[34][u'zh-tw'] = [u'UnTunes', u'UnTunes']
        self.namespaces[34][u'nl'] = [u'Niesiklopedia']
        self.namespaces[34][u'th'] = [u'\u0e44\u0e23\u0e49\u0e20\u0e32\u0e1e']
        self.namespaces[35] = self.namespaces.get(35, {})
        self.namespaces[35][u'pt-br'] = [u'Despoesias Discuss\xe3o']
        self.namespaces[35][u'zh-tw'] = [u'UnTunes\u8a0e\u8ad6', u'UnTunes\u8a0e\u8ad6']
        self.namespaces[35][u'nl'] = [u'Overleg Niesiklopedia']
        self.namespaces[35][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e20\u0e32\u0e1e']
        self.namespaces[36] = self.namespaces.get(36, {})
        self.namespaces[36][u'pt-br'] = [u'Interno']
        self.namespaces[36][u'th'] = [u'\u0e2a\u0e16\u0e32\u0e19\u0e35\u0e22\u0e48\u0e2d\u0e22']
        self.namespaces[37] = self.namespaces.get(37, {})
        self.namespaces[37][u'pt-br'] = [u'Interno Discuss\xe3o']
        self.namespaces[37][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e2a\u0e16\u0e32\u0e19\u0e35\u0e22\u0e48\u0e2d\u0e22']
        self.namespaces[38] = self.namespaces.get(38, {})
        self.namespaces[38][u'pt-br'] = [u'Descifras']
        self.namespaces[38][u'th'] = [u'\u0e44\u0e23\u0e49\u0e19\u0e27\u0e19\u0e34\u0e22\u0e32\u0e22']
        self.namespaces[39] = self.namespaces.get(39, {})
        self.namespaces[39][u'pt-br'] = [u'Descifras Discuss\xe3o']
        self.namespaces[39][u'th'] = [u'\u0e04\u0e38\u0e22\u0e40\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e44\u0e23\u0e49\u0e19\u0e27\u0e19\u0e34\u0e22\u0e32\u0e22']
        self.namespaces[1100] = self.namespaces.get(1100, {})
        self.namespaces[1100][u'el'] = [u'RelatedVideos']
        self.namespaces[1100][u'eo'] = [u'RelatedVideos']
        self.namespaces[1100][u'zh'] = [u'RelatedVideos']
        self.namespaces[1100][u'de'] = [u'Verwandte Videos', u'RelatedVideos']
        self.namespaces[1100][u'it'] = [u'Video collegati', u'RelatedVideos']
        self.namespaces[1100][u'da'] = [u'RelatedVideos']
        self.namespaces[1100][u'sk'] = [u'RelatedVideos']
        self.namespaces[1100][u'fr'] = [u'Vid\xe9os connexes', u'RelatedVideos']
        self.namespaces[1100][u'ar'] = [u'RelatedVideos']
        self.namespaces[1100][u'pl'] = [u'Powi\u0105zane filmy', u'RelatedVideos']
        self.namespaces[1100][u'cs'] = [u'RelatedVideos']
        self.namespaces[1100][u'id'] = [u'RelatedVideos']
        self.namespaces[1100][u'es'] = [u'V\xeddeos relacionados', u'RelatedVideos']
        self.namespaces[1100][u'he'] = [u'RelatedVideos']
        self.namespaces[100] = self.namespaces.get(100, {})
        self.namespaces[100][u'no'] = [u'Ikkenytt']
        self.namespaces[100][u'tr'] = [u'YanS\xf6zl\xfck']
        self.namespaces[100][u'de'] = [u'UnNews', u'Portal', u'Projekt']
        self.namespaces[100][u'ko'] = [u'\uad6c\ubc31\uad34\uac8c\uc784']
        self.namespaces[100][u'sv'] = [u'PsykNyheter']
        self.namespaces[100][u'fa'] = [u'\u062f\u0631\u06af\u0627\u0647', u'\u067e\u0631\u062a\u0627\u0644']
        self.namespaces[100][u'pt-br'] = [u'Descion\xe1rio']
        self.namespaces[100][u'uk'] = [u'\u041f\u0435\u0440\u0435\u0445\u0456\u0434']
        self.namespaces[100][u'gl'] = [u'Desgalicitas']
        self.namespaces[100][u'pl'] = [u'Cytaty']
        self.namespaces[100][u'he'] = [u'\u05d0\u05d9\u05df\u05e6\u05d9\u05d8\u05d5\u05d8']
        self.namespaces[101] = self.namespaces.get(101, {})
        self.namespaces[101][u'no'] = [u'Ikkenytt-diskusjon']
        self.namespaces[101][u'tr'] = [u'YanS\xf6zl\xfck tart\u0131\u015fma']
        self.namespaces[101][u'de'] = [u'UnNews Diskussion', u'Portal Diskussion', u'Projekt Diskussion']
        self.namespaces[101][u'ko'] = [u'\uad6c\ubc31\uad34\uac8c\uc784\ud1a0\ub860']
        self.namespaces[101][u'sv'] = [u'PsykNyheter diskussion']
        self.namespaces[101][u'fa'] = [u'\u0628\u062d\u062b \u062f\u0631\u06af\u0627\u0647']
        self.namespaces[101][u'pt-br'] = [u'Descion\xe1rio Discuss\xe3o']
        self.namespaces[101][u'uk'] = [u'\u041f\u0435\u0440\u0435\u0445\u0456\u0434 \u043e\u0431\u0433']
        self.namespaces[101][u'gl'] = [u'Conversa Desgalicitas']
        self.namespaces[101][u'pl'] = [u'Dyskusja cytat\xf3w']
        self.namespaces[101][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05e6\u05d9\u05d8\u05d5\u05d8']
        self.namespaces[102] = self.namespaces.get(102, {})
        self.namespaces[102][u'en'] = [u'UnNews']
        self.namespaces[102][u'no'] = [u'Ikktionary']
        self.namespaces[102][u'tr'] = [u'YanHaber']
        self.namespaces[102][u'de'] = [u'Undictionary', u'Diverses', u'Forum']
        self.namespaces[102][u'ko'] = [u'\ud3ec\ub7fc', u'\ud3ec']
        self.namespaces[102][u'gl'] = [u'Desgalilibros']
        self.namespaces[102][u'ja'] = [u'UnNews']
        self.namespaces[102][u'pl'] = [u'NonNews']
        self.namespaces[103] = self.namespaces.get(103, {})
        self.namespaces[103][u'en'] = [u'UnNews talk']
        self.namespaces[103][u'no'] = [u'Ikktionary-diskusjon']
        self.namespaces[103][u'tr'] = [u'YanHaber tart\u0131\u015fma']
        self.namespaces[103][u'de'] = [u'Undictionary Diskussion', u'Diverses Diskussion', u'Forum Diskussion']
        self.namespaces[103][u'ko'] = [u'\ud3ec\ub7fc\ud1a0\ub860']
        self.namespaces[103][u'gl'] = [u'Conversa Desgalilibros']
        self.namespaces[103][u'ja'] = [u'UnNews talk']
        self.namespaces[103][u'pl'] = [u'Dyskusja NonNews']
        self.namespaces[104] = self.namespaces.get(104, {})
        self.namespaces[104][u'tlh'] = [u'Holdictionary']
        self.namespaces[104][u'de'] = [u'UnBooks', u'Sub', u'Archiv']
        self.namespaces[104][u'ko'] = [u'\ubc31\uad34\ub274\uc2a4', u'\ub274']
        self.namespaces[104][u'sv'] = [u'Psyktionary']
        self.namespaces[104][u'en'] = [u'Undictionary']
        self.namespaces[104][u'gl'] = [u'Desgalinovas']
        self.namespaces[104][u'ja'] = [u'Undictionary']
        self.namespaces[104][u'pl'] = [u'Non\u017ar\xf3d\u0142a']
        self.namespaces[105] = self.namespaces.get(105, {})
        self.namespaces[105][u'tlh'] = [u"Holdictionary ja'chuq"]
        self.namespaces[105][u'de'] = [u'UnBooks Diskussion', u'Sub Diskussion', u'Archiv Diskussion']
        self.namespaces[105][u'ko'] = [u'\ubc31\uad34\ub274\uc2a4\ud1a0\ub860', u'\ub274\ud1a0']
        self.namespaces[105][u'sv'] = [u'Psyktionary diskussion']
        self.namespaces[105][u'en'] = [u'Undictionary talk']
        self.namespaces[105][u'gl'] = [u'Conversa Desgalinovas']
        self.namespaces[105][u'ja'] = [u'Undictionary talk']
        self.namespaces[105][u'pl'] = [u'Dyskusja non\u017ar\xf3de\u0142']
        self.namespaces[106] = self.namespaces.get(106, {})
        self.namespaces[106][u'tlh'] = [u'GhItNews']
        self.namespaces[106][u'de'] = [u'Spiegelwelten', u'SW', u'Kamelionary']
        self.namespaces[106][u'ko'] = [u'\ubc31\uad34\ub0b1\ub9d0\uc0ac\uc804', u'\ub0b1']
        self.namespaces[106][u'sv'] = [u'PsykCitat']
        self.namespaces[106][u'en'] = [u'Game']
        self.namespaces[106][u'pt-br'] = [u'Desnot\xedcias']
        self.namespaces[106][u'gl'] = [u'Desgalizionario']
        self.namespaces[106][u'ja'] = [u'Game']
        self.namespaces[106][u'pl'] = [u'S\u0142ownik']
        self.namespaces[107] = self.namespaces.get(107, {})
        self.namespaces[107][u'tlh'] = [u"GhItNews ja'chuq"]
        self.namespaces[107][u'de'] = [u'Spiegelwelten Diskussion', u'Kamelionary Diskussion']
        self.namespaces[107][u'ko'] = [u'\ubc31\uad34\ub0b1\ub9d0\uc0ac\uc804\ud1a0\ub860', u'\ub0b1\ud1a0']
        self.namespaces[107][u'sv'] = [u'PsykCitat diskussion']
        self.namespaces[107][u'en'] = [u'Game talk']
        self.namespaces[107][u'pt-br'] = [u'Desnot\xedcias Discuss\xe3o']
        self.namespaces[107][u'gl'] = [u'Conversa Desgalizionario']
        self.namespaces[107][u'ja'] = [u'Game talk']
        self.namespaces[107][u'pl'] = [u'Dyskusja s\u0142ownika']
        self.namespaces[108] = self.namespaces.get(108, {})
        self.namespaces[108][u'en'] = [u'Babel']
        self.namespaces[108][u'ko'] = [u'\ud574\uc124']
        self.namespaces[108][u'de'] = [u'News']
        self.namespaces[108][u'tr'] = [u'Astroloji']
        self.namespaces[108][u'sv'] = [u'Spel']
        self.namespaces[108][u'pl'] = [u'Gra']
        self.namespaces[109] = self.namespaces.get(109, {})
        self.namespaces[109][u'en'] = [u'Babel talk']
        self.namespaces[109][u'ko'] = [u'\ud574\uc124\ud1a0\ub860']
        self.namespaces[109][u'de'] = [u'News Diskussion']
        self.namespaces[109][u'tr'] = [u'Astroloji tart\u0131\u015fma']
        self.namespaces[109][u'sv'] = [u'Speldiskussion']
        self.namespaces[109][u'pl'] = [u'Dyskusja gry']
        self.namespaces[110] = self.namespaces.get(110, {})
        self.namespaces[110][u'el'] = [u'Forum']
        self.namespaces[110][u'sco'] = [u'Forum']
        self.namespaces[110][u'en'] = [u'Forum']
        self.namespaces[110][u'zh'] = [u'Forum']
        self.namespaces[110][u'io'] = [u'Forum']
        self.namespaces[110][u'af'] = [u'Forum']
        self.namespaces[110][u'simple'] = [u'Forum']
        self.namespaces[110][u'oc'] = [u'Forum']
        self.namespaces[110][u'is'] = [u'Forum']
        self.namespaces[110][u'it'] = [u'Forum']
        self.namespaces[110][u'ar'] = [u'Forum']
        self.namespaces[110][u'pt-br'] = [u'Forum', u'F\xf3rum']
        self.namespaces[110][u'km'] = [u'Forum']
        self.namespaces[110][u'eo'] = [u'Forum']
        self.namespaces[110][u'fi'] = [u'Foorumi']
        self.namespaces[110][u'cs'] = [u'Forum']
        self.namespaces[110][u'et'] = [u'Foorum']
        self.namespaces[110][u'gl'] = [u'Forum']
        self.namespaces[110][u'ie'] = [u'Forum']
        self.namespaces[110][u'id'] = [u'Forum']
        self.namespaces[110][u'es'] = [u'Foro', u'Forum']
        self.namespaces[110][u'lb'] = [u'Forum']
        self.namespaces[110][u'lo'] = [u'Forum']
        self.namespaces[110][u'nn'] = [u'Forum']
        self.namespaces[110][u'no'] = [u'Forum']
        self.namespaces[110][u'zh-tw'] = [u'\u8ad6\u58c7', u'\u8ad6\u58c7']
        self.namespaces[110][u'tr'] = [u'Forum']
        self.namespaces[110][u'tl'] = [u'Forum']
        self.namespaces[110][u'li'] = [u'Forum']
        self.namespaces[110][u'lv'] = [u'Forum']
        self.namespaces[110][u'lt'] = [u'Forum']
        self.namespaces[110][u'th'] = [u'Forum']
        self.namespaces[110][u'got'] = [u'Forum']
        self.namespaces[110][u'fo'] = [u'Forum']
        self.namespaces[110][u'pl'] = [u'Forum']
        self.namespaces[110][u'mwl'] = [u'Forum']
        self.namespaces[110][u'fr'] = [u'Forum']
        self.namespaces[110][u'hy'] = [u'Forum']
        self.namespaces[110][u'ms'] = [u'Forum']
        self.namespaces[110][u'hr'] = [u'Forum']
        self.namespaces[110][u'fy'] = [u'Forum']
        self.namespaces[110][u'bn'] = [u'Forum']
        self.namespaces[110][u'de'] = [u'Forum', u'Commons']
        self.namespaces[110][u'mg'] = [u'Forum']
        self.namespaces[110][u'da'] = [u'Forum']
        self.namespaces[110][u'fa'] = [u'Forum']
        self.namespaces[110][u'bs'] = [u'Forum']
        self.namespaces[110][u'nl'] = [u'Forum']
        self.namespaces[110][u'hu'] = [u'Forum']
        self.namespaces[110][u'ja'] = [u'Forum']
        self.namespaces[110][u'he'] = [u'\u05d1\u05d9\u05ea \u05e7\u05e4\u05d4']
        self.namespaces[110][u'ka'] = [u'Forum']
        self.namespaces[110][u'ro'] = [u'Forum']
        self.namespaces[110][u'sr'] = [u'Forum']
        self.namespaces[110][u'mo'] = [u'Forum']
        self.namespaces[110][u'la'] = [u'Forum']
        self.namespaces[110][u'ko'] = [u'Forum']
        self.namespaces[110][u'sv'] = [u'Forum']
        self.namespaces[110][u'mk'] = [u'Forum']
        self.namespaces[110][u'sk'] = [u'Forum']
        self.namespaces[110][u'uk'] = [u'\u0424\u043e\u0440\u0443\u043c']
        self.namespaces[110][u'sl'] = [u'Forum']
        self.namespaces[110][u'tlh'] = [u'Forum']
        self.namespaces[111] = self.namespaces.get(111, {})
        self.namespaces[111][u'el'] = [u'Forum talk']
        self.namespaces[111][u'sco'] = [u'Forum talk']
        self.namespaces[111][u'en'] = [u'Forum talk']
        self.namespaces[111][u'zh'] = [u'Forum talk']
        self.namespaces[111][u'io'] = [u'Forum talk']
        self.namespaces[111][u'af'] = [u'Forum talk']
        self.namespaces[111][u'simple'] = [u'Forum talk']
        self.namespaces[111][u'oc'] = [u'Forum talk']
        self.namespaces[111][u'is'] = [u'Forum talk']
        self.namespaces[111][u'it'] = [u'Forum talk']
        self.namespaces[111][u'ar'] = [u'Forum talk']
        self.namespaces[111][u'pt-br'] = [u'Forum Discuss\xe3o']
        self.namespaces[111][u'km'] = [u'Forum talk']
        self.namespaces[111][u'eo'] = [u'Forum talk']
        self.namespaces[111][u'fi'] = [u'Keskustelu foorumista']
        self.namespaces[111][u'cs'] = [u'Forum talk']
        self.namespaces[111][u'et'] = [u'Forum talk']
        self.namespaces[111][u'gl'] = [u'Conversa Forum']
        self.namespaces[111][u'ie'] = [u'Forum talk']
        self.namespaces[111][u'id'] = [u'Forum talk']
        self.namespaces[111][u'es'] = [u'Foro Discusi\xf3n', u'Forum talk']
        self.namespaces[111][u'lb'] = [u'Forum talk']
        self.namespaces[111][u'lo'] = [u'Forum talk']
        self.namespaces[111][u'nn'] = [u'Forum talk']
        self.namespaces[111][u'no'] = [u'Forum talk']
        self.namespaces[111][u'zh-tw'] = [u'\u8ad6\u58c7\u8a0e\u8ad6', u'\u8ad6\u58c7\u8a0e\u8ad6']
        self.namespaces[111][u'tr'] = [u'Forum tart\u0131\u015fma']
        self.namespaces[111][u'tl'] = [u'Forum talk']
        self.namespaces[111][u'li'] = [u'Forum talk']
        self.namespaces[111][u'lv'] = [u'Forum talk']
        self.namespaces[111][u'lt'] = [u'Forum talk']
        self.namespaces[111][u'th'] = [u'Forum talk']
        self.namespaces[111][u'got'] = [u'Forum gawaurdja']
        self.namespaces[111][u'fo'] = [u'Forum talk']
        self.namespaces[111][u'pl'] = [u'Dyskusja forum', u'Forum talk']
        self.namespaces[111][u'mwl'] = [u'Forum talk']
        self.namespaces[111][u'fr'] = [u'Discussion Forum']
        self.namespaces[111][u'hy'] = [u'Forum talk']
        self.namespaces[111][u'ms'] = [u'Forum talk']
        self.namespaces[111][u'hr'] = [u'Forum talk']
        self.namespaces[111][u'fy'] = [u'Forum talk']
        self.namespaces[111][u'bn'] = [u'Forum talk']
        self.namespaces[111][u'de'] = [u'Forum talk', u'Commons Diskussion']
        self.namespaces[111][u'mg'] = [u'Forum talk']
        self.namespaces[111][u'da'] = [u'Forumdiskussion']
        self.namespaces[111][u'fa'] = [u'Forum talk']
        self.namespaces[111][u'bs'] = [u'Forum talk']
        self.namespaces[111][u'nl'] = [u'Forum talk']
        self.namespaces[111][u'hu'] = [u'Forum talk']
        self.namespaces[111][u'ja'] = [u'Forum talk']
        self.namespaces[111][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d1\u05d9\u05ea \u05e7\u05e4\u05d4']
        self.namespaces[111][u'ka'] = [u'Forum talk']
        self.namespaces[111][u'ro'] = [u'Discu\u021bie Forum']
        self.namespaces[111][u'sr'] = [u'Forum talk']
        self.namespaces[111][u'mo'] = [u'Forum talk']
        self.namespaces[111][u'la'] = [u'Forum talk']
        self.namespaces[111][u'ko'] = [u'Forum talk']
        self.namespaces[111][u'sv'] = [u'Forumdiskussion']
        self.namespaces[111][u'mk'] = [u'Forum talk']
        self.namespaces[111][u'sk'] = [u'Forum talk']
        self.namespaces[111][u'uk'] = [u'\u041e\u0431\u0433\u043e\u0432\u043e\u0440\u0435\u043d\u043d\u044f \u0444\u043e\u0440\u0443\u043c\u0443']
        self.namespaces[111][u'sl'] = [u'Forum talk']
        self.namespaces[111][u'tlh'] = [u"Forum ja'chuq"]
        self.namespaces[112] = self.namespaces.get(112, {})
        self.namespaces[112][u'fr'] = [u'D\xe9sinformation']
        self.namespaces[112][u'gl'] = [u'\xc7ciclop\xe9dia']
        self.namespaces[112][u'zh'] = [u'\u4f2a\u57fa\u65b0\u95fb']
        self.namespaces[112][u'no'] = [u'Hvordan']
        self.namespaces[112][u'de'] = [u'Kamelobooks']
        self.namespaces[112][u'ko'] = [u'\uc138\uacc4\uad00']
        self.namespaces[112][u'it'] = [u'NonNotizie']
        self.namespaces[112][u'sv'] = [u'PsykB\xf6cker']
        self.namespaces[112][u'en'] = [u'UnTunes']
        self.namespaces[112][u'pl'] = [u'Portal']
        self.namespaces[112][u'cs'] = [u'Reg\xe1l']
        self.namespaces[112][u'tlh'] = [u'Tlhbooks']
        self.namespaces[112][u'ja'] = [u'UnTunes']
        self.namespaces[112][u'es'] = [u'Incinoticias']
        self.namespaces[112][u'he'] = [u'\u05d0\u05d9\u05df\u05e1\u05e4\u05e8']
        self.namespaces[113] = self.namespaces.get(113, {})
        self.namespaces[113][u'fr'] = [u'Discussion D\xe9sinformation']
        self.namespaces[113][u'gl'] = [u'Conversa \xc7ciclop\xe9dia']
        self.namespaces[113][u'zh'] = [u'\u4f2a\u57fa\u65b0\u95fb talk']
        self.namespaces[113][u'no'] = [u'Hvordan-diskusjon']
        self.namespaces[113][u'de'] = [u'Kamelobooks Diskussion']
        self.namespaces[113][u'ko'] = [u'\uc138\uacc4\uad00\ud1a0\ub860']
        self.namespaces[113][u'it'] = [u'Discussioni NonNotizie']
        self.namespaces[113][u'sv'] = [u'PsykB\xf6ckerdiskussion']
        self.namespaces[113][u'en'] = [u'UnTunes talk']
        self.namespaces[113][u'pl'] = [u'Dyskusja portalu']
        self.namespaces[113][u'cs'] = [u'Reg\xe1l diskuse']
        self.namespaces[113][u'tlh'] = [u"Tlhbooks ja'chuq"]
        self.namespaces[113][u'ja'] = [u'UnTunes talk']
        self.namespaces[113][u'es'] = [u'Incinoticias Discusi\xf3n']
        self.namespaces[113][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05e1\u05e4\u05e8']
        self.namespaces[114] = self.namespaces.get(114, {})
        self.namespaces[114][u'fr'] = [u'Portail']
        self.namespaces[114][u'en'] = [u'HowTo']
        self.namespaces[114][u'zh'] = [u'\u4f2a\u57fa\u6587\u5e93']
        self.namespaces[114][u'no'] = [u'Hvorfor']
        self.namespaces[114][u'de'] = [u'Frage']
        self.namespaces[114][u'ko'] = [u'\ubc31\uad34\ub300\ud559', u'\ub300']
        self.namespaces[114][u'pl'] = [u'Poradnik']
        self.namespaces[114][u'cs'] = [u'Necykloverzita']
        self.namespaces[114][u'tlh'] = [u'Ninciclopedia']
        self.namespaces[114][u'es'] = [u'Incitables']
        self.namespaces[114][u'he'] = [u'\u05d0\u05d9\u05df\u05d7\u05d3\u05e9']
        self.namespaces[115] = self.namespaces.get(115, {})
        self.namespaces[115][u'fr'] = [u'Discussion Portail']
        self.namespaces[115][u'en'] = [u'HowTo talk']
        self.namespaces[115][u'zh'] = [u'\u4f2a\u57fa\u6587\u5e93 talk']
        self.namespaces[115][u'no'] = [u'Hvorfor-diskusjon']
        self.namespaces[115][u'de'] = [u'Frage Diskussion']
        self.namespaces[115][u'ko'] = [u'\ubc31\uad34\ub300\ud559\ud1a0\ub860', u'\ub300\ud1a0']
        self.namespaces[115][u'pl'] = [u'Dyskusja poradnika']
        self.namespaces[115][u'cs'] = [u'Necykloverzita diskuse']
        self.namespaces[115][u'tlh'] = [u'Ninciclopedia Discussion']
        self.namespaces[115][u'es'] = [u'Incitables Discusi\xf3n']
        self.namespaces[115][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05d7\u05d3\u05e9']
        self.namespaces[116] = self.namespaces.get(116, {})
        self.namespaces[116][u'en'] = [u'Why?']
        self.namespaces[116][u'zh'] = [u'\u4f2a\u57fa\u97f3\u4e50']
        self.namespaces[116][u'no'] = [u'Ikkeratur']
        self.namespaces[116][u'ko'] = [u'\ubc31\uad34\uc778\uc6a9\uc9d1', u'\uc778']
        self.namespaces[116][u'tlh'] = [u'GhItSpecies']
        self.namespaces[116][u'ja'] = [u'UnBooks']
        self.namespaces[116][u'es'] = [u'Incijuegos']
        self.namespaces[116][u'he'] = [u'\u05d0\u05d9\u05df\u05d8\u05e7\u05e1\u05d8']
        self.namespaces[117] = self.namespaces.get(117, {})
        self.namespaces[117][u'en'] = [u'Why? talk']
        self.namespaces[117][u'zh'] = [u'\u4f2a\u57fa\u97f3\u4e50 talk']
        self.namespaces[117][u'no'] = [u'Ikkeratur-Diskusjon']
        self.namespaces[117][u'ko'] = [u'\ubc31\uad34\uc778\uc6a9\uc9d1\ud1a0\ub860', u'\uc778\ud1a0']
        self.namespaces[117][u'tlh'] = [u"GhItSpecies ja'chuq"]
        self.namespaces[117][u'ja'] = [u'UnBooks talk']
        self.namespaces[117][u'es'] = [u'Incijuegos Discusi\xf3n']
        self.namespaces[117][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05d8\u05e7\u05e1\u05d8']
        self.namespaces[118] = self.namespaces.get(118, {})
        self.namespaces[118][u'en'] = [u'UnBooks']
        self.namespaces[118][u'zh'] = [u'\u4f2a\u57fa\u8bcd\u5178']
        self.namespaces[118][u'no'] = [u'Ikkeprosjekt']
        self.namespaces[118][u'ko'] = [u'\ubc31\uad34\ucc45', u'\ucc45']
        self.namespaces[118][u'it'] = [u'Giochi']
        self.namespaces[118][u'tlh'] = [u'Holfacts']
        self.namespaces[118][u'he'] = [u'\u05d1\u05d9\u05ea \u05e7\u05e4\u05d4']
        self.namespaces[119] = self.namespaces.get(119, {})
        self.namespaces[119][u'en'] = [u'UnBooks talk']
        self.namespaces[119][u'zh'] = [u'\u4f2a\u57fa\u8bcd\u5178 talk']
        self.namespaces[119][u'no'] = [u'Ikkeprosjekt-diskusjon']
        self.namespaces[119][u'ko'] = [u'\ubc31\uad34\ucc45\ud1a0\ub860', u'\ucc45\ud1a0']
        self.namespaces[119][u'it'] = [u'Discussioni Giochi']
        self.namespaces[119][u'tlh'] = [u"Holfacts ja'chuq"]
        self.namespaces[119][u'he'] = [u'\u05d1\u05d9\u05ea \u05e7\u05e4\u05d4 \u05e9\u05d9\u05d7\u05ea']
        self.namespaces[120] = self.namespaces.get(120, {})
        self.namespaces[120][u'en'] = [u'UnScripts']
        self.namespaces[120][u'ko'] = [u'\ubc31\uad34\ub300\ubcf8', u'\uadf9']
        self.namespaces[120][u'tr'] = [u'YanMagazin']
        self.namespaces[120][u'it'] = [u'NonCitazioni']
        self.namespaces[120][u'tlh'] = [u'Tlhconversations']
        self.namespaces[120][u'he'] = [u'\u05d0\u05d9\u05df\u05de\u05d9\u05dc\u05d5\u05df']
        self.namespaces[121] = self.namespaces.get(121, {})
        self.namespaces[121][u'en'] = [u'UnScripts talk']
        self.namespaces[121][u'ko'] = [u'\ubc31\uad34\ub300\ubcf8\ud1a0\ub860', u'\uadf9\ud1a0']
        self.namespaces[121][u'tr'] = [u'YanMagazin tart\u0131\u015fma']
        self.namespaces[121][u'it'] = [u'Discussioni NonCitazioni']
        self.namespaces[121][u'tlh'] = [u"Tlhconversations ja'chuq"]
        self.namespaces[121][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05de\u05d9\u05dc\u05d5\u05df']
        self.namespaces[122] = self.namespaces.get(122, {})
        self.namespaces[122][u'pt-br'] = [u'Regra']
        self.namespaces[122][u'en'] = [u'UnPoetia']
        self.namespaces[122][u'ko'] = [u'\ubc29\ubc95']
        self.namespaces[122][u'it'] = [u'NonDizionario']
        self.namespaces[122][u'he'] = [u'\u05d0\u05d9\u05df\u05de\u05d9\u05e0\u05d9\u05dd']
        self.namespaces[123] = self.namespaces.get(123, {})
        self.namespaces[123][u'pt-br'] = [u'Regra Discuss\xe3o']
        self.namespaces[123][u'en'] = [u'UnPoetia talk']
        self.namespaces[123][u'ko'] = [u'\ubc29\ubc95\ud1a0\ub860']
        self.namespaces[123][u'it'] = [u'Discussioni NonDizionario']
        self.namespaces[123][u'he'] = [u'\u05e9\u05d9\u05d7\u05ea \u05d0\u05d9\u05df\u05de\u05d9\u05e0\u05d9\u05dd']
        self.namespaces[124] = self.namespaces.get(124, {})
        self.namespaces[124][u'en'] = [u'Unquotable']
        self.namespaces[124][u'it'] = [u'Test']
        self.namespaces[125] = self.namespaces.get(125, {})
        self.namespaces[125][u'en'] = [u'Unquotable talk']
        self.namespaces[125][u'it'] = [u'Discussioni test']
        self.namespaces[126] = self.namespaces.get(126, {})
        self.namespaces[126][u'en'] = [u'UnDebate']
        self.namespaces[126][u'it'] = [u'NonLibri']
        self.namespaces[127] = self.namespaces.get(127, {})
        self.namespaces[127][u'en'] = [u'UnDebate talk']
        self.namespaces[127][u'it'] = [u'Discussioni NonLibri']
        self.namespaces[128] = self.namespaces.get(128, {})
        self.namespaces[128][u'en'] = [u'UnReviews']
        self.namespaces[128][u'it'] = [u'Manuali']
        self.namespaces[129] = self.namespaces.get(129, {})
        self.namespaces[129][u'en'] = [u'UnReviews talk']
        self.namespaces[129][u'it'] = [u'Discussioni manuali']
        self.namespaces[130] = self.namespaces.get(130, {})
        self.namespaces[130][u'en'] = [u'UnVoyage']
        self.namespaces[130][u'it'] = [u'Portale']
        self.namespaces[131] = self.namespaces.get(131, {})
        self.namespaces[131][u'en'] = [u'UnVoyage talk']
        self.namespaces[131][u'it'] = [u'Discussioni portale']
        self.namespaces[150] = self.namespaces.get(150, {})
        self.namespaces[150][u'pt-br'] = [u'Deslistas']
        self.namespaces[151] = self.namespaces.get(151, {})
        self.namespaces[151][u'pt-br'] = [u'Deslistas Discuss\xe3o']
        self.namespaces[1200] = self.namespaces.get(1200, {})
        self.namespaces[1200][u'el'] = [u'Message Wall']
        self.namespaces[1200][u'eo'] = [u'Message Wall']
        self.namespaces[1200][u'zh'] = [u'Message Wall']
        self.namespaces[1200][u'de'] = [u'Nachrichtenseite', u'Message Wall']
        self.namespaces[1200][u'it'] = [u'Bacheca', u'Message Wall']
        self.namespaces[1200][u'da'] = [u'Message Wall']
        self.namespaces[1200][u'sk'] = [u'Message Wall']
        self.namespaces[1200][u'fr'] = [u'Mur', u'Message Wall']
        self.namespaces[1200][u'ar'] = [u'Message Wall']
        self.namespaces[1200][u'pl'] = [u'Tablica wiadomo\u015bci', u'Message Wall']
        self.namespaces[1200][u'cs'] = [u'Message Wall']
        self.namespaces[1200][u'id'] = [u'Message Wall']
        self.namespaces[1200][u'es'] = [u'Muro', u'Message Wall']
        self.namespaces[1200][u'he'] = [u'Message Wall']
        self.namespaces[1201] = self.namespaces.get(1201, {})
        self.namespaces[1201][u'el'] = [u'Thread']
        self.namespaces[1201][u'eo'] = [u'Thread']
        self.namespaces[1201][u'zh'] = [u'Thread']
        self.namespaces[1201][u'de'] = [u'Diskussionsfaden', u'Thread']
        self.namespaces[1201][u'it'] = [u'Thread']
        self.namespaces[1201][u'da'] = [u'Thread']
        self.namespaces[1201][u'sk'] = [u'Thread']
        self.namespaces[1201][u'fr'] = [u'Fil', u'Thread']
        self.namespaces[1201][u'ar'] = [u'Thread']
        self.namespaces[1201][u'pl'] = [u'W\u0105tek', u'Thread']
        self.namespaces[1201][u'cs'] = [u'Thread']
        self.namespaces[1201][u'id'] = [u'Thread']
        self.namespaces[1201][u'es'] = [u'Hilo', u'Thread']
        self.namespaces[1201][u'he'] = [u'Thread']
        self.namespaces[1202] = self.namespaces.get(1202, {})
        self.namespaces[1202][u'el'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'eo'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'zh'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'de'] = [u'Nachrichtenseite Begr\xfc\xdfung', u'Message Wall Greeting']
        self.namespaces[1202][u'it'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'da'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'sk'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'fr'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'ar'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'pl'] = [u'Nag\u0142\xf3wek tablicy', u'Message Wall Greeting']
        self.namespaces[1202][u'cs'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'id'] = [u'Message Wall Greeting']
        self.namespaces[1202][u'es'] = [u'Bienvenida del Muro', u'Message Wall Greeting']
        self.namespaces[1202][u'he'] = [u'Message Wall Greeting']
        self.namespaces[274] = self.namespaces.get(274, {})
        self.namespaces[274][u'de'] = [u'Widget', u'Widget']
        self.namespaces[275] = self.namespaces.get(275, {})
        self.namespaces[275][u'de'] = [u'Widget Diskussion', u'Widget talk']
        self.namespaces[420] = self.namespaces.get(420, {})
        self.namespaces[420][u'af'] = [u'Layer']
        self.namespaces[420][u'mwl'] = [u'Layer']
        self.namespaces[421] = self.namespaces.get(421, {})
        self.namespaces[421][u'af'] = [u'Layer talk']
        self.namespaces[421][u'mwl'] = [u'Layer talk']
        self.namespaces[-1] = self.namespaces.get(-1, {})
        self.namespaces[-1][u'eo'] = [u'Speciala']
        self.namespaces[-1][u'zh'] = [u'\u7279\u6b8a']
        self.namespaces[-1][u'ms'] = [u'Istimewa']
        self.namespaces[-1][u'mwl'] = [u'Especial']
        self.namespaces[-1][u'zh-tw'] = [u'\u7279\u6b8a', u'\u7279\u6b8a']
        self.namespaces[-1][u'ko'] = [u'\ud2b9']
        self.namespaces[-1][u'mk'] = [u'\u0421\u043f\u0435\u0446\u0438\u0458\u0430\u043b\u043d\u0438']
        self.namespaces[-1][u'pt-br'] = [u'Especial']
        self.namespaces[-1][u'uk'] = [u'\u0421\u043f\u0435\u0446\u0456\u0430\u043b\u044c\u043d\u0456']
        self.namespaces[-1][u'sr'] = [u'Posebno']
        self.namespaces[-1][u'tlh'] = [u'Special']
        self.namespaces[-1][u'fo'] = [u'Serstakur']
        self.namespaces[500] = self.namespaces.get(500, {})
        self.namespaces[500][u'el'] = [u'User blog']
        self.namespaces[500][u'eo'] = [u'User blog']
        self.namespaces[500][u'zh'] = [u'User blog']
        self.namespaces[500][u'de'] = [u'Benutzer Blog', u'User blog']
        self.namespaces[500][u'fr'] = [u'Blog utilisateur', u'User blog']
        self.namespaces[500][u'da'] = [u'User blog']
        self.namespaces[500][u'sk'] = [u'User blog']
        self.namespaces[500][u'ar'] = [u'User blog']
        self.namespaces[500][u'cs'] = [u'User blog']
        self.namespaces[500][u'id'] = [u'User blog']
        self.namespaces[500][u'es'] = [u'Usuario Blog', u'User blog']
        self.namespaces[500][u'he'] = [u'User blog']
        self.namespaces[501] = self.namespaces.get(501, {})
        self.namespaces[501][u'el'] = [u'User blog comment']
        self.namespaces[501][u'eo'] = [u'User blog comment']
        self.namespaces[501][u'zh'] = [u'User blog comment']
        self.namespaces[501][u'de'] = [u'Benutzer Blog Kommentare', u'User blog comment']
        self.namespaces[501][u'fr'] = [u'Commentaire blog utilisateur', u'User blog comment']
        self.namespaces[501][u'da'] = [u'User blog comment']
        self.namespaces[501][u'sk'] = [u'User blog comment']
        self.namespaces[501][u'ar'] = [u'User blog comment']
        self.namespaces[501][u'cs'] = [u'User blog comment']
        self.namespaces[501][u'id'] = [u'User blog comment']
        self.namespaces[501][u'es'] = [u'Usuario Blog Comentario', u'User blog comment']
        self.namespaces[501][u'he'] = [u'User blog comment']
        self.namespaces[502] = self.namespaces.get(502, {})
        self.namespaces[502][u'el'] = [u'Blog']
        self.namespaces[502][u'eo'] = [u'Blog']
        self.namespaces[502][u'zh'] = [u'Blog']
        self.namespaces[502][u'de'] = [u'Blog']
        self.namespaces[502][u'fr'] = [u'Blog']
        self.namespaces[502][u'da'] = [u'Blog']
        self.namespaces[502][u'sk'] = [u'Blog']
        self.namespaces[502][u'ar'] = [u'Blog']
        self.namespaces[502][u'cs'] = [u'Blog']
        self.namespaces[502][u'id'] = [u'Blog']
        self.namespaces[502][u'es'] = [u'Blog']
        self.namespaces[502][u'he'] = [u'Blog']
        self.namespaces[503] = self.namespaces.get(503, {})
        self.namespaces[503][u'el'] = [u'Blog talk']
        self.namespaces[503][u'eo'] = [u'Blog talk']
        self.namespaces[503][u'zh'] = [u'Blog talk']
        self.namespaces[503][u'de'] = [u'Blog Diskussion', u'Blog talk']
        self.namespaces[503][u'fr'] = [u'Discussion blog utilisateur', u'Blog talk']
        self.namespaces[503][u'da'] = [u'Blog talk']
        self.namespaces[503][u'sk'] = [u'Blog talk']
        self.namespaces[503][u'ar'] = [u'Blog talk']
        self.namespaces[503][u'cs'] = [u'Blog talk']
        self.namespaces[503][u'id'] = [u'Blog talk']
        self.namespaces[503][u'es'] = [u'Blog Discusi\xf3n', u'Blog talk']
        self.namespaces[503][u'he'] = [u'Blog talk']
        self.namespaces[-2] = self.namespaces.get(-2, {})
        self.namespaces[-2][u'el'] = [u'\u039c\u03ad\u03c3\u03bf\u03bd']
        self.namespaces[-2][u'mg'] = [u'M\xe9dia']
        self.namespaces[-2][u'zh'] = [u'\u5a92\u4f53', u'\u5a92\u9ad4']
        self.namespaces[-2][u'lo'] = [u'\u0eaa\u0eb7\u0ec8\u0ead']
        self.namespaces[-2][u'zh-tw'] = [u'\u5a92\u9ad4', u'\u5a92\u9ad4']
        self.namespaces[-2][u'bs'] = [u'Medija']
        self.namespaces[-2][u'tr'] = [u'Medya']
        self.namespaces[-2][u'mk'] = [u'\u041c\u0435\u0434\u0438\u0458\u0430']
        self.namespaces[-2][u'fa'] = [u'\u0631\u0633\u0627\u0646\u0647', u'\u0631\u0633\u0627\u0646\u0647\u200c\u0627\u06cc']
        self.namespaces[-2][u'ar'] = [u'\u0648\u0633\u0627\u0626\u0637']
        self.namespaces[-2][u'pt-br'] = [u'M\xeddia']
        self.namespaces[-2][u'km'] = [u'\u1798\u17b8\u178c\u17b6']
        self.namespaces[-2][u'sr'] = [u'\u041c\u0435\u0434\u0438\u0458\u0430', u'Medija']
        self.namespaces[-2][u'tlh'] = [u'Media']


    def scriptpath(self, code):
        return {
            'ar': u'',
            'lb': u'',
            'is': u'',
            'uk': u'',
            'mo': u'',
            'hy': u'',
            'sl': u'',
            'fo': u'',
            'th': u'',
            'fa': u'',
            'zh': u'',
            'de': u'',
            'no': u'',
            'ko': u'/w',
            'el': u'',
            'it': u'',
            'zh-tw': u'',
            'gl': u'',
            'tlh': u'',
            'hr': u'',
            'sr': u'',
            'he': u'',
            'bn': u'',
            'simple': u'',
            'sk': u'',
            'ka': u'',
            'sco': u'',
            'sv': u'',
            'ja': u'',
            'mwl': u'',
            'lt': u'',
            'zh-tw': u'',
            'tl': u'',
            'eo': u'',
            'oc': u'',
            'ms': u'',
            'bs': u'',
            'es': u'',
            'de': u'',
            'pl': u'',
            'ie': u'',
            'da': u'',
            'ro': u'',
            'li': u'',
            'nn': u'',
            'mg': u'',
            'la': u'',
            'id': u'',
            'lo': u'',
            'io': u'',
            'de': u'',
            'fy': u'',
            'en': u'/w',
            'tr': u'',
            'mk': u'',
            'cs': u'',
            'km': u'',
            'af': u'',
            'nl': u'',
            'et': u'',
            'got': u'',
            'lv': u'',
            'pt-br': u'',
            'hu': u'',
            'fr': u'',
            'fi': u'',
        }[code]

    def version(self, code):
        return {
            'ar': u'1.19.3',
            'lb': u'1.20alpha',
            'is': u'1.20alpha',
            'uk': u'1.20alpha',
            'mo': u'1.20alpha',
            'hy': u'1.20alpha',
            'sl': u'1.20alpha',
            'fo': u'1.20alpha',
            'th': u'1.20alpha',
            'fa': u'1.20alpha',
            'zh': u'1.19.3',
            'de': u'1.19.3',
            'no': u'1.20alpha',
            'ko': u'1.21alpha',
            'el': u'1.19.3',
            'it': u'1.19.3',
            'zh-tw': u'1.20alpha',
            'gl': u'1.20alpha',
            'tlh': u'1.20alpha',
            'hr': u'1.20alpha',
            'sr': u'1.20alpha',
            'he': u'1.19.3',
            'bn': u'1.20alpha',
            'simple': u'1.20alpha',
            'sk': u'1.19.3',
            'ka': u'1.20alpha',
            'sco': u'1.20alpha',
            'sv': u'1.20alpha',
            'ja': u'1.20alpha',
            'mwl': u'1.20alpha',
            'lt': u'1.20alpha',
            'zh-tw': u'1.20alpha',
            'tl': u'1.20alpha',
            'eo': u'1.19.3',
            'oc': u'1.20alpha',
            'ms': u'1.20alpha',
            'bs': u'1.20alpha',
            'es': u'1.19.3',
            'de': u'1.18.5',
            'pl': u'1.19.3',
            'ie': u'1.20alpha',
            'da': u'1.19.3',
            'ro': u'1.20alpha',
            'li': u'1.20alpha',
            'nn': u'1.20alpha',
            'mg': u'1.20alpha',
            'la': u'1.20alpha',
            'id': u'1.19.3',
            'lo': u'1.20alpha',
            'io': u'1.20alpha',
            'de': u'1.18.1',
            'fy': u'1.20alpha',
            'en': u'1.20.2',
            'tr': u'1.20alpha',
            'mk': u'1.20alpha',
            'cs': u'1.19.3',
            'km': u'1.20alpha',
            'af': u'1.20alpha',
            'nl': u'1.20alpha',
            'et': u'1.20alpha',
            'got': u'1.20alpha',
            'lv': u'1.20alpha',
            'pt-br': u'1.20alpha',
            'hu': u'1.20alpha',
            'fr': u'1.19.3',
            'fi': u'1.20alpha',
        }[code]
